### ISSUE TITLE
需要讨论问题的规则

### ISSUE THREAD

**Issue by RikkaW** [RikkaApps/StorageRedirect-assets#1]
- `com.hippo.ehviewer`
@FoobarRogers ehviewer 其实挺特别的，又可以通过系统的文档写入，又可以使用普通的方式。是不是需要更多的说明比较好？

- `com.xunlei.downloadprovider`
@geng9301 为什么是从 obb 里面出来？

**Comment by OldFanta** [comment]
因为迅雷下载的默认储存位置就是 sd/Android/obb/com.xunlei.downloadprovider/文件。
