### ISSUE TITLE
[New rules request][AUTO] com.baidu.input

### ISSUE THREAD

**Issue by duzhaokun123** [RikkaApps/StorageRedirect-assets#1019]
## Application information
 - Package name: `com.baidu.input`
 - Display name: 百度输入法
 - Version: 8.1.0.7 (180)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_SG_#Hans
 - Storage Redirect app version: 0.17.4-beta.r848.2384374d-armeabi-v7a (8481)
 ## JSON Output
 ```
 {
  "package": "com.baidu.input",
  "recommended": true,
  "verified": false,
  "authors": [
    "duzhaokun123"
  ]
}
 ```

**Comment by XZ-Dev** [comment]
## Application information
 - Package name: `com.baidu.input`
 - Display name: 百度输入法
 - Version: 8.2.1.12 (182)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: zh_CN
 - Storage Redirect app version: 0.18.0-beta.r915.57348058-arm64-v8a (9152)
 ## JSON Output
 ```
 {
  "package": "com.baidu.input",
  "recommended": true,
  "verified": false,
  "authors": [
    "XZ-Dev"
  ]
}
 ```
