### ISSUE TITLE
[SR Bug] 部分规则不生效

### ISSUE THREAD

**Issue by CloudxM** [RikkaApps/StorageRedirect-assets#1026]
1.微博国际版
问题：视频保存规则已勾选但是未生效
包名：com.weico.international
视频被保存在：WeiboInternational/weiboIntl_video
应该保存在：Movie/weiboIntl

2.MyAndroidTools Pro
包名：cn.wq.myandroidtoolspro
行为：应用备份规则已勾选但是未生效
数据被保存在：Android/data/cn.wq.myandroidtoolspro/sdcard/MyAndroidTools
应该保存在：Documents/MyAndroidTools

3.MyAndroidTools
包名：cn.wq.myandroidtools
行为：应用备份规则已勾选但是未生效
数据被保存在：Android/data/cn.wq.myandroidtoolspro/sdcard 的目录下
应该保存在：Documents/MyAndroidTools

**Comment by CloudxM** [comment]
@RikkaW @RikkaAppsBot

**Comment by CloudxM** [comment]
@fython 是的，在本机测试，规则开启了，但是没按预期的目录工作。

**Comment by lshilshi** [comment]
> @CloudxM 两个问题都是规则路径无误但不生效吗？

> @fython 是的，在本机测试，规则开启了，但是没按预期的目录工作。

问题复现！
我同时用的MAT助手，一样是设定好规则路径无误但不生效。

还有就是微信的Mask（文件名过滤）也应该是无误但不生效。

**Comment by CloudxM** [comment]
@fython 发现又漏了个MyAndroidTools普通版的规则
包名：cn.wq.myandroidtools
行为：应用备份规则已勾选但是未生效
数据被保存在：Android / data / cn.wq.myandroidtoolspro / sdcard / 目录下
应该保存在：Documents / MyAndroidToos

**Comment by fython** [comment]
@CloudxM 这个是正常行为，请阅读 Storage Redirect 的官方帮助文档了解如何工作。

**Comment by CloudxM** [comment]
@fython 好的，明白了，除了新浪微博视频规则的问题，其他规则已经补上了，可以关闭此issues了。
