### ISSUE TITLE
[SR Bug] 链接功能失效及可能的失效原因

### ISSUE THREAD

**Issue by PaperFlu** [RikkaApps/StorageRedirect-assets#1040]
开启了 Log 然后找到了这行：

08-14 13:34:16.397 I/StorageRedirect(11155): Can't link /data/media/0/Android/data/me.pkhope.longscreenshot/sdcard/LongScreenshot/180814-133416.jpeg to /data/media/0/Pictures/LongScreenshot/180814-133416.jpeg

为什么是 /data/media/0/ ？不应该是 /storage/emulated/0/ 吗？（前一行：）

08-14 13:34:16.326 V/StorageRedirect(11155): Event: create in source, path=/storage/emulated/0/Android/data/me.pkhope.longscreenshot/sdcard/LongScreenshot/180814-133416.jpeg

（接着这两行的第三行：）

08-14 13:34:16.397 I/StorageRedirect(11155): android.system.ErrnoException: link failed: ENOENT (No such file or directory)

希望能有帮助😀

**Comment by PaperFlu** [comment]
0.18.1beta 也没有用

**Comment by PaperFlu** [comment]
0.18.2beta 不管用
估计0.18.3beta 也不行

**Comment by RikkaW** [comment]
关于 /data/media，/storage/emulated 是由 /data/media 经过各种东西变出来的（所以也就叫 emulated）。

最一开始是监控 /data/media，后来（0.18.0 0.18.1）改成了 /storage/emulated，但是在有的人那里监控 /storage/emulated 没有用，所以又改回了 /data/media（0.18.2）。

ENOENT (No such file or directory) 的话，试试从 /data/media 开始一层层 ls 看看是不是真的有这个文件存在。

另外那一串 log 能不能都发上来呀（

**Comment by PaperFlu** [comment]
@RikkaW 额.. 差点把这 issue 给忘了。

Log 见附件，主要看 2 个：
* Aug 14 的是 0.18.0 的，这里可以找到 link 语句。
* Aug 22 的是 0.18.2 的。link 不见了不知道怎么回事。
  20 号那天凌晨我也做过一次 0.18.2 的，也是找不到 link，但是过几个小时回来一看找到了。这条我手抽删掉了。

你说 0.18.0-1 改成了 /storage/emulated，可是这里看来好像并没有。是不是要清应用数据什么的。

/data/media 含的是 /0/storage/emulated/Pictures/LongScreenshot，但里面并没有文件。
/storage/emulated/0/Android/data/me.pkhope.longscreenshot/sdcard/LongScreenshot 里可有 8 个。

[Aug 14, 2018 13352 PM.log](https://github.com/RikkaApps/StorageRedirect-assets/files/2309341/Aug.14.2018.13352.PM.log)
[Aug 14, 2018 14935 PM.log](https://github.com/RikkaApps/StorageRedirect-assets/files/2309342/Aug.14.2018.14935.PM.log)
[Aug 19, 2018 112138 AM.log](https://github.com/RikkaApps/StorageRedirect-assets/files/2309343/Aug.19.2018.112138.AM.log)
[Aug 20, 2018 101458 AM.log](https://github.com/RikkaApps/StorageRedirect-assets/files/2309344/Aug.20.2018.101458.AM.log)
[Aug 20, 2018 124054 AM.log](https://github.com/RikkaApps/StorageRedirect-assets/files/2309345/Aug.20.2018.124054.AM.log)
[Aug 22, 2018 22348 PM.log](https://github.com/RikkaApps/StorageRedirect-assets/files/2309346/Aug.22.2018.22348.PM.log)

**Comment by RikkaW** [comment]
```
su
ls /data/media/0/Android/data/me.pkhope.longscreenshot/sdcard/LongScreenshot
ls /data/media/0/Pictures
ls /data/media/0/Pictures/LongScreenshot
```
会出现什么呢

**Comment by PaperFlu** [comment]
不好意思😂 我之前打错了
/data/media 含的是 /0/Pictures/LongScreenshot，里面并没有文件。
我可以直接告诉你 /data/media/0/ 里只有 Pictures/，再里面又只有 LongScreenshot/，在里面是空的。
不存在任何 Android/

**Comment by RikkaW** [comment]
所以你的 /storage/emulated 并不来自于 /data/media 吗
```
su
mount | grep storage
```
会出来什么呢

**Comment by PaperFlu** [comment]
@RikkaW 
会出来：

``
tmpfs on /storage type tmpfs (rw,seclabel,relatime,size=916528k,nr_inodes=229132,mode=755,gid=1000)
/mnt/expand/69b8d3c2-cf5c-44bd-95ce-c1a50f931d4d/media on /storage/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7)
tmpfs on /storage/self type tmpfs (rw,seclabel,relatime,size=916528k,nr_inodes=229132,mode=755,gid=1000)
``

对了，我的 Internal Storage 是 SD card 经过 Format as internal 变来的（安卓 6.0？7.0？后自带的，在连接不认识的 SD 后会自动打开操作选择界面，或手动在 Settings - Storage - SD card 里点击菜单三点 - 选择 Format as internal）。

**Comment by PaperFlu** [comment]
加个微信吧，不然这么麻烦。

**Comment by PaperFlu** [comment]
问题解决。可以关闭了。
