### ISSUE TITLE
[New rules request][AUTO] com.youdao.calculator

### ISSUE THREAD

**Issue by Sodium-Aluminate** [RikkaApps/StorageRedirect-assets#1115]
## Application information
 - Package name: `com.youdao.calculator`
 - Display name: 超级计算器
 - Version: 2.0.0 (20001)
 ## User rules
 - `recommended`: No
 - `verified`: Yes
 - Reason: 建议直接禁止读写权限。
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.18.2-beta.r945.67fb4022-arm64-v8a (9452)
 ## JSON Output
 ```
 {
  "package": "com.youdao.calculator",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN": "建议直接禁止读写权限。"
  },
  "authors": [
    "Sodium-Aluminate"
  ]
}
 ```

**Comment by OpportunityLiu** [comment]
这种最好能做成单独一种提示
