### ISSUE TITLE
仅重定向部分文件夹请求

### ISSUE THREAD

**Issue by Sodium-Aluminate** [RikkaApps/StorageRedirect-assets#1125]
FV悬浮球(com.fooview.android.fooview)会在存储卡根目录建立 /.fooview/ 文件夹，但同时有“文件管理”功能。
因此请求：能不能只重定向 .fooview 文件夹而不重定向任何其他文件夹？

**Comment by marikid** [comment]
:sweat_smile: 要用文件管理功能就不要重定向了嘛。FV 几乎所有文件都放在 .fooview 里，还算挺良心的。
