### ISSUE TITLE
[New rules request][AUTO] com.evenwell.DbgCfgTool

### ISSUE THREAD

**Issue by fayeniko** [RikkaApps/StorageRedirect-assets#1162]
## Application information
- Package name: `com.evenwell.DbgCfgTool`
- Display name: DbgCfgTool
- Version: 9.0010.04 (9001004)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: en_US
- Storage Redirect app version: 1.0.0-rc5.r1098.6ae1390d-arm64-v8a (10982)
## JSON Output
```
{
  "package": "com.evenwell.DbgCfgTool",
  "recommended": false,
  "verified": true,
  "authors": [
    "fayeniko"
  ]
}
```

**Comment by CloudxM** [comment]
## Application information
- Package name: `com.evenwell.DbgCfgTool`
- Display name: DbgCfgTool
- Version: 9.0010.04 (9001004)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 系统自带应用，建议添加可信任。
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN_#Hans
- Storage Redirect app version: 1.0.0-rc5.r1098.6ae1390d-arm64-v8a (10982)
## JSON Output
```
{
  "package": "com.evenwell.DbgCfgTool",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN_#Hans": "系统自带应用，建议添加可信任。"
  },
  "authors": [
    "CloudxM"
  ]
}
```

**Comment by CloudxM** [comment]
## Application information
- Package name: `com.evenwell.DbgCfgTool`
- Display name: DbgCfgTool
- Version: 8.0010.12 (8001012)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 系统应用，建议添加认证。
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN_#Hans
- Storage Redirect app version: 1.0.0-rc7.r1111.662b9f84-arm64-v8a (11112)
## JSON Output
```
{
  "package": "com.evenwell.DbgCfgTool",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN_#Hans": "系统应用，建议添加认证。"
  },
  "authors": [
    "CloudxM"
  ]
}
```
