### ISSUE TITLE
[New rules request][AUTO] com.evenwell.bboxsbox.app

### ISSUE THREAD

**Issue by fayeniko** [RikkaApps/StorageRedirect-assets#1163]
## Application information
- Package name: `com.evenwell.bboxsbox.app`
- Display name: BBox
- Version: 9.0010.01 (9)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: en_US
- Storage Redirect app version: 1.0.0-rc5.r1098.6ae1390d-arm64-v8a (10982)
## JSON Output
```
{
  "package": "com.evenwell.bboxsbox.app",
  "recommended": false,
  "verified": true,
  "authors": [
    "fayeniko"
  ]
}
```

**Comment by CloudxM** [comment]
## Application information
- Package name: `com.evenwell.bboxsbox.app`
- Display name: BBox
- Version: 9.0010.01 (9)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 系统应用，建议添加可信任。
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN_#Hans
- Storage Redirect app version: 1.0.0-rc5.r1098.6ae1390d-arm64-v8a (10982)
## JSON Output
```
{
  "package": "com.evenwell.bboxsbox.app",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN_#Hans": "系统应用，建议添加可信任。"
  },
  "authors": [
    "CloudxM"
  ]
}
```
