### ISSUE TITLE
[New rules request][AUTO] com.brave.browser

### ISSUE THREAD

**Issue by kpwd** [RikkaApps/StorageRedirect-assets#1191]
## Application information
- Package name: `com.brave.browser`
- Display name: Brave
- Version: 1.0.19 (1011)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 7.1.2 (API 25)
- User language: zh_CN
- Storage Redirect app version: 1.0.0-rc8.r1117.972ed6f3-arm64-v8a (11172)
## JSON Output
```
{
  "package": "com.brave.browser",
  "recommended": false,
  "verified": true,
  "authors": [
    "kpwd"
  ]
}
```

**Comment by YaBoiBurner** [comment]
## Application information
- Package name: `com.brave.browser`
- Display name: Brave
- Version: 1.0.58 (1082)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: en_US
- Storage Redirect app version: 1.0.0-rc8.r1117.972ed6f3-arm64-v8a (11172)
## JSON Output
```
{
  "package": "com.brave.browser",
  "recommended": false,
  "verified": true,
  "authors": [
    "YaBoiBurner"
  ]
}
```
