### ISSUE TITLE
[New rules request][AUTO] com.fkzhang.qqxposed

### ISSUE THREAD

**Issue by rly61** [RikkaApps/StorageRedirect-assets#121]
## Application information
 - Package name: `com.fkzhang.qqxposed`
 - Display name: QXposed
 - Version: 1.18 (19)
 ## User rules
 - `recommended`: No
 - `verified`: No
 - Reason: 备注:该应用会在外部存储创建文件。但若QQ重定向了，则只会在QQ已重定向的根目录里创建。
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.0 (API 24)
 - User language: zh_CN
 - Storage Redirect app version: 0.12.1-beta.r483.dbf3e30 (483)
 ## JSON Output
 ```
 {
     "package": "com.fkzhang.qqxposed",
     "recommended": false,
     "verified": false,
     "authors": ["rly61"],
     "reason": {"zh_CN": "备注:该应用会在外部存储创建文件。但若QQ重定向了，则只会在QQ已重定向的根目录里创建。"},
     "observers": [
 
     ]
 }
 ```

**Comment by fython** [comment]
@rly61 该应用会产生什么文件，可以在此评论补充一下吗？备注有点看不懂。

**Comment by rly61** [comment]
该应用会创建程序本身设置文件。
该程序是QQ xposed插件，应该是利用QQ进程创建的。
如果QQ重定向了，则会创建在QQ重定向目录下cache/sdcard/QxSettings文件；如果QQ没有重定向，则会创建在sd根目录下，sdcard/QxSettings文件。
