### ISSUE TITLE
MagiskManger规则修改

### ISSUE THREAD

**Issue by snailwind** [RikkaApps/StorageRedirect-assets#1210]
- 应用包名：（com.topjohnwu.magisk）
- 应用标题：（Magisk Manger）
- 应用版本：（5.9.0+）

- 规则问题描述：（旧版下载新建下载文件夹，新版更新后下载文件夹已改为Download系统默认文件夹了）
- 规则修改建议：（此规则已无意义  该APP已无新建文件夹行为）

**Comment by shanefengcn** [comment]
#1224
