### ISSUE TITLE
[New rules request][AUTO] com.fkzhang.wechatxposed

### ISSUE THREAD

**Issue by rly61** [RikkaApps/StorageRedirect-assets#122]
## Application information
 - Package name: `com.fkzhang.wechatxposed`
 - Display name: WeXposed
 - Version: 1.18 (23)
 ## User rules
 - `recommended`: No
 - `verified`: No
 - Reason: 备注:该应用会在外部存储创建文件。但若WeChat重定向了，则只会在WeChat重定向根目录里创建。所以它是否在外部存储创建文件取决于WeChat的重定向设置，该应用设置与否无法影响。
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.0 (API 24)
 - User language: zh_CN
 - Storage Redirect app version: 0.12.1-beta.r483.dbf3e30 (483)
 ## JSON Output
 ```
 {
     "package": "com.fkzhang.wechatxposed",
     "recommended": false,
     "verified": false,
     "authors": ["rly61"],
     "reason": {"zh_CN": "备注:该应用会在外部存储创建文件。但若WeChat重定向了，则只会在WeChat重定向根目录里创建。所以它是否在外部存储创建文件取决于WeChat的重定向设置，该应用设置与否无法影响。"},
     "observers": [
 
     ]
 }
 ```

**Comment by fython** [comment]
@rly61 该应用会产生什么文件，可以在此评论补充一下吗？备注有点看不懂。

**Comment by rly61** [comment]
该应用会创建程序本身设置文件。
该程序是微信xposed插件，应该是利用微信进程创建的。
如果微信重定向了，则会创建在微信重定向目录下cache/sdcard/WechatXposed文件夹；如果微信没有重定向，则会创建在sd根目录下。

**Comment by rly61** [comment]
@fython 都不影响

**Comment by fython** [comment]
@rly61 感谢提供规则，稍后就会加入。
