### ISSUE TITLE
[New rules request][AUTO] org.tvp.kirikiri2_free_10309

### ISSUE THREAD

**Issue by lifansama** [RikkaApps/StorageRedirect-assets#1261]
## Application information
- Package name: `org.tvp.kirikiri2_free_10309`
- Display name: 吉里吉里2模拟器 1.3.9
- Version: 1.3.9 (68)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.0.1.r1188.a2c9c00d-arm64-v8a (11882)
## JSON Output
```
{
  "package": "org.tvp.kirikiri2_free_10309",
  "recommended": false,
  "verified": true,
  "authors": [
    "lifansama"
  ]
}
```

**Comment by ForbAvalon** [comment]
## Application information
- Package name: `org.tvp.kirikiri2_free_10309`
- Display name: 吉里吉里2模拟器 1.3.9
- Version: 1.3.9 (68)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 极度不推荐开启。开启后必须将相关游戏文件放在对应目录中，导致在卸载应用时相关游戏文件被删除，也会导致文件更容易被文件清理软件删除。
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.0.1.r1188.a2c9c00d-armeabi-v7a (11881)
## JSON Output
```
{
  "package": "org.tvp.kirikiri2_free_10309",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN": "极度不推荐开启。开启后必须将相关游戏文件放在对应目录中，导致在卸载应用时相关游戏文件被删除，也会导致文件更容易被文件清理软件删除。"
  },
  "authors": [
    "ForbAvalon"
  ]
}
```
