### ISSUE TITLE
[Invalid verified app][AUTO] com.mxtech.videoplayer.ad

### ISSUE THREAD

**Issue by ggehuliang** [RikkaApps/StorageRedirect-assets#1412]
## Application information - Package name: `com.mxtech.videoplayer.ad` - Version: 1.9.20 (1310001042) ## Reason - Path: `/storage/emulated/0/Subtitles`

**Comment by fython** [comment]
That could be an acceptable behavior although `Subtitles` is not a standard folder.

**Comment by yiheng0** [comment]
## Application information - Package name: `com.mxtech.videoplayer.ad` - Version: 1.10.30 (1310001100) ## Reason - Path: `/storage/emulated/0/Subtitles`

**Comment by Riddle233** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.9.20 (1310001042)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by GSAlex** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.43 (1310001113)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by mgsqz** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.33 (1810001103)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by CatMe0w** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.47 (1310001117)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by xiaobaitang** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.44 (1810001114)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by xiaobaitang** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.44 (1810001114)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by Clear-up** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.51 (1310001121)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by PaperFlu** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.60 (1310001130)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by 1071239216** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.60 (1310001130)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by 1071239216** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.60 (1310001130)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by 1071239216** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.60 (1310001130)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by RogerReal** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.60 (1310001130)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by RyoNanamizu** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.60 (1310001130)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by whc200187** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.10.60 (1310001130)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by Youxikong** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.11.3 (1310001134)
## Reason
- Path: `/storage/emulated/0/.ColombiaMedia`

**Comment by satanruiko** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.11.3 (1310001134)
## Reason
- Path: `/storage/emulated/0/.ColombiaMedia`

**Comment by AokiFuru** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.11.6 (1310001137)
## Reason
- Path: `/storage/emulated/0/.ColombiaMedia`

**Comment by Hill-98** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.11.6 (1310001137)
## Reason
- Path: `/storage/emulated/0/.ColombiaMedia`

**Comment by Hill-98** [comment]
## Application information
- Package name: `com.mxtech.videoplayer.ad`
- Version: 1.11.6 (1310001137)
## Reason
- Path: `/storage/emulated/0/.ColombiaMedia`
