### ISSUE TITLE
[New rules request][AUTO] com.android.browser

### ISSUE THREAD

**Issue by pzcn** [RikkaApps/StorageRedirect-assets#1426]
## Application information
- Package name: `com.android.browser`
- Display name: 浏览器
- Version: 10.2.7 (20181022)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.0.2.r1204.f2752e1e-arm64-v8a (12042)
## JSON Output
```
{
  "package": "com.android.browser",
  "recommended": true,
  "verified": false,
  "authors": [
    "PedroZhang"
  ]
}
```

**Comment by Vstory** [comment]
## Application information - Package name: `com.android.browser` - Display name: 浏览器 - Version: 10.3.3 (20181126) ## User rules - `recommended`: Yes - `verified`: No - Reason: 在根目录创建文件夹广告过滤屏蔽文件 ### ObserverInfo No observers. ## More information - Android version: 8.1.0 (API 27) - User language: zh_CN - Storage Redirect app version: 1.2.2.r1370.6beebe9c-arm64-v8a (13702) ## JSON Output ``` {
  "package": "com.android.browser",
  "recommended": true,
  "verified": false,
  "description": {
    "zh_CN": "在根目录创建文件夹广告过滤屏蔽文件"
  },
  "authors": [
    "Vstory"
  ]
} ```

**Comment by chisakaw** [comment]
## Application information - Package name: `com.android.browser` - Display name: 浏览器 - Version: 10.2.11 (20181029) ## User rules - `recommended`: Yes - `verified`: No - Reason:  ### ObserverInfo No observers. ## More information - Android version: 8.0.0 (API 26) - User language: zh_CN - Storage Redirect app version: 1.3.1.r1402.e08d0637-arm64-v8a (14022) ## JSON Output ``` {
  "package": "com.android.browser",
  "recommended": true,
  "verified": false,
  "authors": [
    "chisakaw"
  ]
} ```

**Comment by lishuda** [comment]
## Application information - Package name: `com.android.browser` - Display name: Browser - Version: 10.2.4 (20181008) ## User rules - `recommended`: No - `verified`: No - Reason: it's just for the browser about miui ### ObserverInfo No observers. ## More information - Android version: 8.0.0 (API 26) - User language: en_US - Storage Redirect app version: 1.3.2.r1403.25edc048-arm64-v8a (14032) ## JSON Output ``` {
  "package": "com.android.browser",
  "recommended": false,
  "verified": false,
  "description": {
    "en_US": "it\u0027s just for the browser about miui"
  },
  "authors": [
    "lishuda"
  ]
} ```

**Comment by Stalaxy** [comment]
## Application information
- Package name: `com.android.browser`
- Display name: 浏览器
- Version: 5.0.57 (418070001)
## User rules
- `recommended`: {recommended}
- `verified`: no
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.0.r1821.2df28430-arm64-v8a (18212)
## JSON Output
```
{
  "package": "com.android.browser",
  "recommend": true,
  "verified": false,
  "authors": [
    "Stalaxy"
  ]
}
```
