### ISSUE TITLE
Unable to start service.

### ISSUE THREAD

**Issue by sgqy** [RikkaApps/StorageRedirect-assets#1428]
```
Hardware: Xiaomi 6X
  System: MIUI dev 10.2 by xiaomi.eu 8.11.1
    Root: Magisk 17.3
Settings: Enabled dual app

Always 'Loading', restart app will get freezed black screen. Magisk is never triggered.
```

**Comment by sgqy** [comment]
It seems magick has some issue. :thinking:

**Comment by laerhu** [comment]
Thanks for you sharing. Same questions, solved by "restore images" with the unistall button at the bottom of magisk manager front page.

Hardware: Xiaomi 9se
  System: MIUI stable 11.05 by xiaomi.eu based on android 9
    Root: Magisk 20.1

Start failed, Unable to open root shell. Magisk is never triggered.
