### ISSUE TITLE
[Invalid verified app][AUTO] nextapp.fx

### ISSUE THREAD

**Issue by zzndb** [RikkaApps/StorageRedirect-assets#1434]
## Application information - Package name: `nextapp.fx` - Version: 7.2.2.2 (7211) ## Reason - Path: `/storage/emulated/0/tbs`

**Comment by fython** [comment]
**FX File Manager** is a file manager app so its major behavior is produced by users. Currently we cannot ensure if its verified mark should be removed.

**Comment by lnothe** [comment]
## Application information
- Package name: `nextapp.fx`
- Version: 7.2.2.2 (7211)
## Reason
- Path: `/storage/emulated/0/NAD/rule/nextapp.fx/nextapp.fx.ui.ExplorerActivity`

**Comment by 1683787723** [comment]
## Application information
- Package name: `nextapp.fx`
- Version: 7.2.2.2 (7211)
## Reason
- Path: `/storage/emulated/0/data/user/0/com.yulore.framework/files/offlineData/flag`
