### ISSUE TITLE
[Invalid verified app][AUTO] com.ktls.fileinfo

### ISSUE THREAD

**Issue by Aotola** [RikkaApps/StorageRedirect-assets#1435]
## Application information - Package name: `com.ktls.fileinfo` - Version: 4.4.5 (112) ## Reason - Path: `/storage/emulated/0/dctp`

**Comment by fython** [comment]
It is a clean-manager-like app.

**Comment by david082321** [comment]
## Application information - Package name: `com.ktls.fileinfo` - Version: 4.4.7 (114) ## Reason - Path: `/storage/emulated/0/Android/obj/.um`

**Comment by hjthjthjt** [comment]
## Application information - Package name: `com.ktls.fileinfo` - Version: 4.4.9 (116) ## Reason - Path: `/storage/emulated/0/tmsdual_shark_mq.bat`

**Comment by cjjdaq** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.4.9 (116)
## Reason
- Path: `/storage/emulated/0/.UTSystemConfig/Global/Alvin2.xml`

**Comment by ExcitedEven** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.4.9 (116)
## Reason
- Path: `/storage/emulated/0/.UTSystemConfig/Global/Alvin2.xml`

**Comment by ExcitedEven** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.4.9 (116)
## Reason
- Path: `/storage/emulated/0/ooudide`

**Comment by caryle** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.5.1 (118)
## Reason
- Path: `/storage/emulated/0/Android/obj/.um`

**Comment by caryle** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.5.1 (118)
## Reason
- Path: `/storage/emulated/0/Android/obj/.um`

**Comment by afeigorgor** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.5.1 (118)
## Reason
- Path: `/storage/emulated/0/Android/obj/.um`

**Comment by 1683787723** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.5.3 (120)
## Reason
- Path: `/storage/emulated/0/.UTSystemConfig/Global/Alvin2.xml`

**Comment by shacha086** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.5.3 (120)
## Reason
- Path: `/storage/emulated/0/backups`

**Comment by KyokuAsahi** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.5.3 (120)
## Reason
- Path: `/storage/emulated/0/albumSelect/b5659eb691f8ccc8582a3c7f6bd67275.temp`

**Comment by cornsailing** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.5.7 (123)
## Reason
- Path: `/storage/emulated/0/.turing.dat`

**Comment by naicfeng** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.5.8 (124)
## Reason
- Path: `/storage/emulated/0/Tencent`

**Comment by 1294266616** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.5.9 (125)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp.lock`

**Comment by 1294266616** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.6.0 (126)
## Reason
- Path: `/storage/emulated/0/powercfg_panel.txt`

**Comment by sghcf** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.6.1 (127)
## Reason
- Path: `/storage/emulated/0/backups/.nomedia`

**Comment by sghcf** [comment]
## Application information
- Package name: `com.ktls.fileinfo`
- Version: 4.6.1 (127)
## Reason
- Path: `/storage/emulated/0/.DataStorage/ContextData.xml`
