### ISSUE TITLE
[Invalid verified app][AUTO] com.mixplorer

### ISSUE THREAD

**Issue by OKOMPer** [RikkaApps/StorageRedirect-assets#1438]
## Application information - Package name: `com.mixplorer` - Version: 6.29.20 (1810311) ## Reason - Path: `/storage/emulated/0/test1542160096070`

**Comment by OKOMPer** [comment]
## Application information - Package name: `com.mixplorer` - Version: 6.29.20 (1810311) ## Reason - Path: `/storage/emulated/0/.recycle/1540633296785.3/data`

**Comment by fython** [comment]
It is a file-manager-like app.
