### ISSUE TITLE
[Invalid verified app][AUTO] mark.via

### ISSUE THREAD

**Issue by Melencolia11514** [RikkaApps/StorageRedirect-assets#1443]
## Application information - Package name: `mark.via` - Version: 3.4.5 (20181110) ## Reason - Path: `/storage/emulated/0/WechatXposed/WxSettings`

**Comment by mwdotzom** [comment]
## Application information
- Package name: `mark.via`
- Version: 3.9.2 (20190723)
## Reason
- Path: `/storage/emulated/0/NAD/rule/mark.via/mark.via.ui.activity.BrowserActivity`
