### ISSUE TITLE
[Invalid verified app][AUTO] com.android.providers.downloads

### ISSUE THREAD

**Issue by ShadowLyin** [RikkaApps/StorageRedirect-assets#1480]
## Application information - Package name: `com.android.providers.downloads` - Version: 9 (28) ## Reason - Path: `/storage/emulated/0/albumthumbs`

**Comment by Aotola** [comment]
## Application information - Package name: `com.android.providers.downloads` - Version: 8.09.20.800001 (80920001) ## Reason - Path: `/storage/emulated/0/360/`

**Comment by Melencolia11514** [comment]
## Application information - Package name: `com.android.providers.downloads` - Version: 8.09.20.800001 (80920001) ## Reason - Path: `/storage/emulated/0/.dlprovider//seq_id`

**Comment by Vstory** [comment]
## Application information - Package name: `com.android.providers.downloads` - Version: 8.11.14.800002 (81114002) ## Reason - Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by Vstory** [comment]
## Application information - Package name: `com.android.providers.downloads` - Version: 8.11.14.800002 (81114002) ## Reason - Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by Juicpt** [comment]
## Application information - Package name: `com.android.providers.downloads` - Version: 8.12.03.800003 (81203003) ## Reason - Path: `/storage/emulated/0/mipush/lcfp.lock`

**Comment by Riddle233** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.01.24.800001 (90124001)
## Reason
- Path: `/storage/emulated/0/.dlprovider//statstorage_v5.xml`

**Comment by Vstory** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 8.12.03.800003 (81203003)
## Reason
- Path: `/storage/emulated/0/.dlprovider//statstorage_v5.xml`

**Comment by ExcitedEven** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/Playlists`

**Comment by 597627264** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 8.11.07.800002 (81107002)
## Reason
- Path: `/storage/emulated/0/.dlprovider//seq_id`

**Comment by Juicpt** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.01.24.800003 (90124003)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by iamdennisme** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/.estrongs/recycle/1551090454175/storage/emulated/0/es_recycle_content/AllenVersionPath`

**Comment by Ahaochan** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 7.11.08.800001 (71108001)
## Reason
- Path: `/storage/emulated/0/.dlprovider//statstorage_v5.xml`

**Comment by Ahaochan** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 7.11.08.800001 (71108001)
## Reason
- Path: `/storage/emulated/0/.dlprovider//seq_id`

**Comment by RunningMelos** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.01.24.800004 (90124004)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by Vstory** [comment]
不建议重定向，会影响下载的正常功能

**Comment by benzBrake** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/.woodpecker/general`

**Comment by lesir831** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.03.07.800001 (90307001)
## Reason
- Path: `/storage/emulated/0/.dlprovider`

**Comment by type-95** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 8.11.07.800002 (81107002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by SkyBeautiful** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.03.22.800001 (90322001)
## Reason
- Path: `/storage/emulated/0/MiMarket/files/apk/AutoUpdate`

**Comment by lilongsky** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.03.22.800001 (90322001)
## Reason
- Path: `/storage/emulated/0/Tencent/MicroMsg/WeiXin/mmexport1556645722343.jpg`

**Comment by Clear-up** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.03.22.800001 (90322001)
## Reason
- Path: `/storage/emulated/0/.dlprovider`

**Comment by jallenlau** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.01.24.800003 (90124003)
## Reason
- Path: `/storage/emulated/0/FastHub/magisk-riru-storage-redirect-v19.5.zip.midownload`

**Comment by Fooooox** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/em/energy`

**Comment by qianguoren** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.04.28.800003 (90428003)
## Reason
- Path: `/storage/emulated/0/.dlprovider//seq_id`

**Comment by 2302998733** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/FastHub/magisk-EdXposed-SandHook-v0.4.3.7_alpha-release.zip`

**Comment by baobao1270** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.05.16.800002 (90516002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by kid-oh** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/android/data/com.oneplus.gallery/recyclebin/6398ea4e96af90e1ee881eea92f22a1d5b10a526.config`

**Comment by sakuraSK** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.07.16.800001 (90716001)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by sakuraSK** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.07.16.800001 (90716001)
## Reason
- Path: `/storage/emulated/0/.dlprovider`

**Comment by xpduyson** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20190803-WA0020.jpg`

**Comment by xpduyson** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20190803-WA0022.jpg`

**Comment by Cyclonekid** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.07.26.800002 (90726002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by captaindiaowei** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/android/data/com.oneplus.gallery/recyclebin/8b194a6293feaa35c69aad9e998c46e5d1d7e644.config`

**Comment by neoblackxt** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.07.26.800002 (90726002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by JustAnotherID** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.08.16.800001 (90816001)
## Reason
- Path: `/storage/emulated/0/MIUI`

**Comment by WallBreakerNO4** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.08.20.800002 (90820002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by wjc1577** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.08.20.800002 (90820002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by wjc1577** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.08.20.800002 (90820002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by cjcyx** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/MiMarket/files/apk`

**Comment by Mrright024** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/.dlprovider`

**Comment by zzl-8180** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/duilite`

**Comment by zzl-8180** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/Fonts`

**Comment by zzl-8180** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/Subtitles`

**Comment by GltHud** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by GltHud** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by cjlcdl** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.01.24.800003 (90124003)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by cjlcdl** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.01.24.800003 (90124003)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by wqk317** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.23.800001 (90923001)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by ZeroYe** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.08.20.800002 (90820002)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by Cy324** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/GanGuo/images`

**Comment by Cy324** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/GanGuo`

**Comment by Cy324** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/GanGuo/images`

**Comment by Cy324** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/GanGuo/images/resize,w_480&`

**Comment by StarXu** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.23.800002 (90923002)
## Reason
- Path: `/storage/emulated/0/.dlprovider`

**Comment by Csrayz** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 10 (29)
## Reason
- Path: `/storage/emulated/0/.DataStorage`

**Comment by Csrayz** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 10 (29)
## Reason
- Path: `/storage/emulated/0/AllenVersionPath`

**Comment by 1294266616** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.07.01.800002 (90701002)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by wqk317** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.10.18.800002 (91018002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by blackjack946** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by SoDebug** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.10.18.800002 (91018002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by SoDebug** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.10.18.800002 (91018002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by xuepiaowei** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.07.16.800001 (90716001)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by 1294266616** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.07.01.800002 (90701002)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by 1294266616** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.07.01.800002 (90701002)
## Reason
- Path: `/storage/emulated/0/MiMarket/files/apk/AutoUpdate/QunQun_v2.0.0017_721.apk`

**Comment by Ashinch** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 10 (29)
## Reason
- Path: `/storage/emulated/0/Record/PhoneRecord/+8618577149386`

**Comment by 1683787723** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 8.1.0 (27)
## Reason
- Path: `/storage/emulated/0/data/user/0/com.yulore.framework/files/offlineData/flag`

**Comment by XuHomey** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.10.18.800002 (91018002)
## Reason
- Path: `/storage/emulated/0/miband`

**Comment by XuHomey** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.10.18.800002 (91018002)
## Reason
- Path: `/storage/emulated/0/miband/mibandnotify`

**Comment by XuHomey** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.10.18.800002 (91018002)
## Reason
- Path: `/storage/emulated/0/mipush`

**Comment by XuHomey** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.10.18.800002 (91018002)
## Reason
- Path: `/storage/emulated/0/ramdump`

**Comment by mwdotzom** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 10 (29)
## Reason
- Path: `/storage/emulated/0/.mcs`

**Comment by luoshuijs** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.01.24.800003 (90124003)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by iamdennisme** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 10 (29)
## Reason
- Path: `/storage/emulated/0/didi/file`

**Comment by Alekc233** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.10.18.800002 (91018002)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by Aoba-Kokona** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/.turingdebug`

**Comment by a927050047** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/AndroLua`

**Comment by a927050047** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800002 (90916002)
## Reason
- Path: `/storage/emulated/0/AndroLua`

**Comment by 1683787723** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 8.1.0 (27)
## Reason
- Path: `/storage/emulated/0/data/user/0/com.yulore.framework/files/offlineData/flag`

**Comment by Ashinch** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 10 (29)
## Reason
- Path: `/storage/emulated/0/OSSLog`

**Comment by Ashinch** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 10 (29)
## Reason
- Path: `/storage/emulated/0/.mcs`

**Comment by Engineer1012** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/android/data/com.oneplus.gallery/recyclebin/cc8f377201aa198255ce2ab6f87037b1259f9121.lock`

**Comment by 1294266616** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.07.19.800001 (90719001)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by HinataKato** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.11.01.800001 (91101001)
## Reason
- Path: `/storage/emulated/0/MIUI/.wallpaper_history`

**Comment by fm922** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.11.01.800001 (91101001)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by greenhat616** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 10 (29)
## Reason
- Path: `/storage/emulated/0/tv.danmaku.bili`

**Comment by H-olxx** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.07.19.800001 (90719001)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by mqz233** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.12.06.800002 (91206002)
## Reason
- Path: `/storage/emulated/0/baidu/tempdata`

**Comment by etnperlong** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.09.16.800003 (90916003)
## Reason
- Path: `/storage/emulated/0/AppTimer`

**Comment by shawnleetttt** [comment]
## Application information
- Package name: `com.android.providers.downloads`
- Version: 9.05.24.800002 (90524002)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by OrbitPortal** [comment]
## Application information - Package name: `com.android.providers.downloads` - Version: 10 (29) ## Reason - Path: `/storage/emulated/0/Geetest`

**Comment by H-olxx** [comment]
## Application information - Package name: `com.android.providers.downloads` - Version: 9.07.19.800001 (90719001) ## Reason - Path: `/storage/emulated/0/.dlprovider`

**Comment by xuepiaowei** [comment]
## Application information - Package name: `com.android.providers.downloads` - Version: 9.12.06.800002 (91206002) ## Reason - Path: `/storage/emulated/0/backups`

**Comment by qiyuey** [comment]
## Application information - Package name: `com.android.providers.downloads` - Version: 9.09.16.800005 (90916005) ## Reason - Path: `/storage/emulated/0/mipush/lcfp.lock`

**Comment by qiyuey** [comment]
## Application information - Package name: `com.android.providers.downloads` - Version: 20.04.20.800003 (200420003) ## Reason - Path: `/storage/emulated/0/tencent/tbs/com.fenbi.android.zenglish`
