### ISSUE TITLE
[Invalid verified app][AUTO] com.android.mms

### ISSUE THREAD

**Issue by xxoolm** [RikkaApps/StorageRedirect-assets#1566]
## Application information - Package name: `com.android.mms` - Version: 10.0.0.1 (10000001) ## Reason - Path: `/storage/emulated/0/mipush/lcfp.lock`

**Comment by qq79480765** [comment]
## Application information - Package name: `com.android.mms` - Version: 9.5.0.54 (9050054) ## Reason - Path: `/storage/emulated/0/mipush/lcfp`

**Comment by Keriteal** [comment]
## Application information - Package name: `com.android.mms` - Version: 10.2.0.28 (10020028) ## Reason - Path: `/storage/emulated/0/mipush/lcfp`

**Comment by Juicpt** [comment]
## Application information - Package name: `com.android.mms` - Version: 10.2.0.56 (10020056) ## Reason - Path: `/storage/emulated/0/mipush/lcfp.lock`

**Comment by xuepiaowei** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 10.1.0.59 (10010059)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by yaojia25** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 10.1.0.86 (10010086)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by Juicpt** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 10.2.0.90 (10020090)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by cutares** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 10.1.0.86 (10010086)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp.lock`

**Comment by draplater** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 10.1.0.95 (10010095)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by RunningMelos** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 10.2.1.2 (10020102)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by SoDebug** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 7.3.5 (7003005)
## Reason
- Path: `/storage/emulated/0/JuphoonService/log`

**Comment by aklover00** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 10.1.0.86 (10010086)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by XiaoQ161** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 10.3.0.6 (10030006)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by xuepiaowei** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 10.3.1.78 (10030178)
## Reason
- Path: `/storage/emulated/0/MIUI/Mms`

**Comment by GltHud** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 11.0.0.1 (11000001)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by L-Ryland** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 11.0.0.1 (11000001)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by sbgyth** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 11.0.0.1 (11000001)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by wqk317** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 11.0.0.26 (11000026)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by zym013579** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 11.0.0.24 (11000024)
## Reason
- Path: `/storage/emulated/0/mipush`

**Comment by 1294266616** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 10.3.1.95 (10030195)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by GltHud** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 11.0.0.1 (11000001)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by XuHomey** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 11.0.0.26 (11000026)
## Reason
- Path: `/storage/emulated/0/mipush`

**Comment by shawnleetttt** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 11.0.0.85 (11000085)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by res-256** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 11.0.1.19 (11000119)
## Reason
- Path: `/storage/emulated/0/MIUI/Mms`

**Comment by shawnleetttt** [comment]
## Application information
- Package name: `com.android.mms`
- Version: 11.0.1.19 (11000119)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`
