### ISSUE TITLE
[Invalid verified app][AUTO] me.weishu.exp

### ISSUE THREAD

**Issue by david082321** [RikkaApps/StorageRedirect-assets#1644]
## Application information - Package name: `me.weishu.exp` - Version: 女娲石·3.6.2 (362) ## Reason - Path: `/storage/emulated/0/AllenVersionPath`

**Comment by JAustinal** [comment]
## Application information - Package name: `me.weishu.exp` - Version: 女娲石·3.6.2 (362) ## Reason - Path: `/storage/emulated/0/AllenVersionPath`
