### ISSUE TITLE
[New rules request][AUTO] com.google.android.soundpicker

### ISSUE THREAD

**Issue by MillionFS** [RikkaApps/StorageRedirect-assets#1703]
## Application information - Package name: `com.google.android.soundpicker` - Display name: Sounds - Version: 2.0 (223598125) (20001403) ## User rules - `recommended`: No - `verified`: Yes - Reason: 这是pixel系统的声音app，没有吐垃圾行为 ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.2.2.r1370.6beebe9c-arm64-v8a (13702) ## JSON Output ``` {
  "package": "com.google.android.soundpicker",
  "recommended": false,
  "verified": true,
  "description": {
    "en_US": "这是pixel系统的声音app，没有吐垃圾行为"
  },
  "authors": [
    "MillionFS"
  ]
} ```

**Comment by OzzyThorne** [comment]
## Application information - Package name: `com.google.android.soundpicker` - Display name: 音效 - Version: 2.0 (223598125) (20001403) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.2.2.r1370.6beebe9c-arm64-v8a (13702) ## JSON Output ``` {
  "package": "com.google.android.soundpicker",
  "recommended": false,
  "verified": true,
  "authors": [
    "OzzyThorne"
  ]
} ```

**Comment by GodofHope** [comment]
## Application information - Package name: `com.google.android.soundpicker` - Display name: 音效 - Version: 2.0 (223598125) (20001403) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN - Storage Redirect app version: 1.3.1.r1402.e08d0637-arm64-v8a (14022) ## JSON Output ``` {
  "package": "com.google.android.soundpicker",
  "recommended": false,
  "verified": true,
  "authors": [
    "GodofHope"
  ]
} ```

**Comment by fayeniko** [comment]
## Application information - Package name: `com.google.android.soundpicker` - Display name: Sounds - Version: 2.0 (223598125) (20001403) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.3.2.r1403.25edc048-arm64-v8a (14032) ## JSON Output ``` {
  "package": "com.google.android.soundpicker",
  "recommended": false,
  "verified": true,
  "authors": [
    "fayeniko"
  ]
} ```

**Comment by fayeniko** [comment]
## Application information - Package name: `com.google.android.soundpicker` - Display name: Sounds - Version: 2.0 (223598125) (20001403) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.google.android.soundpicker",
  "recommended": false,
  "verified": true,
  "authors": [
    "fayeniko"
  ]
} ```

**Comment by GodofHope** [comment]
## Application information - Package name: `com.google.android.soundpicker` - Display name: 音效 - Version: 2.0 (223598125) (20001403) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.google.android.soundpicker",
  "recommended": false,
  "verified": true,
  "authors": [
    "GodofHope"
  ]
} ```

**Comment by YaBoiBurner** [comment]
## Application information - Package name: `com.google.android.soundpicker` - Display name: Sounds - Version: 2.0 (223598125) (20001403) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.google.android.soundpicker",
  "recommended": false,
  "verified": true,
  "authors": [
    "YaBoiBurner"
  ]
} ```

**Comment by Minyooo** [comment]
## Application information - Package name: `com.google.android.soundpicker` - Display name: 音效 - Version: 2.0 (223598125) (20001403) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.google.android.soundpicker",
  "recommended": false,
  "verified": true,
  "authors": [
    "Minyooo"
  ]
} ```
