### ISSUE TITLE
[New rules request][AUTO] org.bromite.bromite

### ISSUE THREAD

**Issue by MicroMe4** [RikkaApps/StorageRedirect-assets#1728]
## Application information - Package name: `org.bromite.bromite` - Display name: Bromite - Version: 71.0.3578.98 (1544577205) ## User rules - `recommended`: No - `verified`: Yes - Reason: Bromite 是一个浏览器，其下载行为不应当认定为创建不标准文件（夹） ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN - Storage Redirect app version: 1.3.1.r1402.e08d0637-arm64-v8a (14022) ## JSON Output ``` {
  "package": "org.bromite.bromite",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN": "Bromite 是一个浏览器，其下载行为不应当认定为创建不标准文件（夹）"
  },
  "authors": [
    "MicroMe4"
  ]
} ```

**Comment by YaBoiBurner** [comment]
## Application information - Package name: `org.bromite.bromite` - Display name: Bromite - Version: 71.0.3578.104 (1545182005) ## User rules - `recommended`: No - `verified`: Yes - Reason: It's a Chrome ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "org.bromite.bromite",
  "recommended": false,
  "verified": true,
  "description": {
    "en_US": "It\u0027s a Chrome"
  },
  "authors": [
    "YaBoiBurner"
  ]
} ```
