### ISSUE TITLE
[New rules request][AUTO] com.uzero.baimiaog

### ISSUE THREAD

**Issue by lifansama** [RikkaApps/StorageRedirect-assets#1733]
## Application information - Package name: `com.uzero.baimiaog` - Display name: 白描 - Version: 2.2.5 (225) ## User rules - `recommended`: Yes - `verified`: No - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN_#Hans - Storage Redirect app version: 1.3.1.r1402.e08d0637-arm64-v8a (14022) ## JSON Output ``` {
  "package": "com.uzero.baimiaog",
  "recommended": true,
  "verified": false,
  "authors": [
    "lifansama"
  ]
} ```

**Comment by Vstory** [comment]
## Application information - Package name: `com.uzero.baimiaog` - Display name: 白描 - Version: 2.2.5 (225) ## User rules - `recommended`: Yes - `verified`: No - Reason: 360加固等sdk ### ObserverInfo No observers. ## More information - Android version: 8.1.0 (API 27) - User language: zh_CN - Storage Redirect app version: 1.3.1.r1402.e08d0637-arm64-v8a (14022) ## JSON Output ``` {
  "package": "com.uzero.baimiaog",
  "recommended": true,
  "verified": false,
  "description": {
    "zh_CN": "360加固等sdk"
  },
  "authors": [
    "Vstory"
  ]
} ```

**Comment by wenxuantao** [comment]
## Application information - Package name: `com.uzero.baimiaog` - Display name: 白描 - Version: 2.2.6 (226) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.uzero.baimiaog",
  "recommended": false,
  "verified": true,
  "authors": [
    "wenxuantao"
  ]
} ```

**Comment by wenxuantao** [comment]
## Application information - Package name: `com.uzero.baimiaog` - Display name: 白描 - Version: 2.2.6 (226) ## User rules - `recommended`: Yes - `verified`: No - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.uzero.baimiaog",
  "recommended": true,
  "verified": false,
  "authors": [
    "wenxuantao"
  ]
} ```

**Comment by Isaccliberty** [comment]
## Application information - Package name: `com.uzero.baimiaog` - Display name: 白描 - Version: 2.3.0 (230) ## User rules - `recommended`: Yes - `verified`: No - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_HK_#Hans - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.uzero.baimiaog",
  "recommended": true,
  "verified": false,
  "authors": [
    "Isaccliberty"
  ]
} ```
