### ISSUE TITLE
[New rules request][AUTO] com.supercell.brawlstars

### ISSUE THREAD

**Issue by HiyoriTUK** [RikkaApps/StorageRedirect-assets#1739]
## Application information - Package name: `com.supercell.brawlstars` - Display name: Brawl Stars - Version: 14.100 (28) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN - Storage Redirect app version: 1.3.1.r1402.e08d0637-arm64-v8a (14022) ## JSON Output ``` {
  "package": "com.supercell.brawlstars",
  "recommended": false,
  "verified": true,
  "authors": [
    "HiyoriTUK"
  ]
} ```

**Comment by 472714747** [comment]
## Application information - Package name: `com.supercell.brawlstars` - Display name: Brawl Stars - Version: 14.118 (30) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 8.0.0 (API 26) - User language: zh_CN_#Hans - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.supercell.brawlstars",
  "recommended": false,
  "verified": true,
  "authors": [
    "472714747"
  ]
} ```

**Comment by piscesmk2013** [comment]
## Application information - Package name: `com.supercell.brawlstars` - Display name: Brawl Stars - Version: 14.118 (30) ## User rules - `recommended`: No - `verified`: Yes - Reason: 该程序不会产生无用文件夹 ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_TW_#Hant - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.supercell.brawlstars",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_TW_#Hant": "该程序不会产生无用文件夹"
  },
  "authors": [
    "piscesmk2013"
  ]
} ```
