### ISSUE TITLE
[New rules request][AUTO] com.bilibili.qing

### ISSUE THREAD

**Issue by Love4Taylor** [RikkaApps/StorageRedirect-assets#1748]
## Application information - Package name: `com.bilibili.qing` - Display name: 轻视频 - Version: 1.0.0 (100000) ## User rules - `recommended`: Yes - `verified`: No - Reason: B站轻视频 App, 拉了一堆屎 ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.3.2.r1403.25edc048-arm64-v8a (14032) ## JSON Output ``` {
  "package": "com.bilibili.qing",
  "recommended": true,
  "verified": false,
  "description": {
    "en_US": "B站轻视频 App, 拉了一堆屎"
  },
  "authors": [
    "Love4Taylor"
  ]
} ```

**Comment by chisakaw** [comment]
## Application information - Package name: `com.bilibili.qing` - Display name: 轻视频 - Version: 1.0.0 (100000) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 8.0.0 (API 26) - User language: zh_CN - Storage Redirect app version: 1.3.2.r1403.25edc048-arm64-v8a (14032) ## JSON Output ``` {
  "package": "com.bilibili.qing",
  "recommended": false,
  "verified": true,
  "authors": [
    "chisakaw"
  ]
} ```
