### ISSUE TITLE
新版本好像会导致封号。。。

### ISSUE THREAD

**Issue by yoyoyosoro** [RikkaApps/StorageRedirect-assets#1756]
- 应用包名：（必填，填入出现问题的应用包名，不知道如何获得包名可以通过“App Ops”应用查看）
- 应用标题：（必填，填入应用显示名称）
- 应用版本：（尽量填写，填入规则不符合的应用版本，如能提供官方何时更新版本更好）

- 规则问题描述：（必填，可选上传屏幕截图）
- 规则修改建议：（必填）

- 规则代码修改建议：（可选，需要完整的规则 JSON 代码）

**（填写完毕后请将模版中所有带括号的文字删除）**

**Comment by G1337663816** [comment]
你这样发出来合适嘛…

**Comment by yoyoyosoro** [comment]
看错了，我还以为是只反馈一个规则的。。
