### ISSUE TITLE
[Invalid verified app][AUTO] com.google.android.apps.translate

### ISSUE THREAD

**Issue by fayeniko** [RikkaApps/StorageRedirect-assets#1765]
## Application information - Package name: `com.google.android.apps.translate` - Version: 5.25.1.RC06.220517201 (59250662) ## Reason - Path: `/storage/2360-16E2/Android/data/com.google.android.apps.translate/files/tmp_dir_should_be_removed`

**Comment by fython** [comment]
Same problem as #1776
