### ISSUE TITLE
刺激战场12.21版本后，重定向导致封号

### ISSUE THREAD

**Issue by yoyoyosoro** [RikkaApps/StorageRedirect-assets#1767]
- 应用包名：com.tencent.tmgp.pubgmhd
- 应用标题：绝地求生 刺激战场
- 应用版本：0.12.5

- 规则问题描述：正常运行，开局秒封号
- 规则修改建议：没啥建议，，，建议先把规则删了吧

-

**Comment by YandexStudio** [comment]
更新以后你们有遇到Appops弹窗询问录音，不管允许还是拒绝，回来之后都无法触摸的问题吗？
如果更新加了太多打着反作弊旗号的反人类操作，那么应该直接把规则改成建议卸载游戏
