### ISSUE TITLE
[Invalid verified app][AUTO] com.google.android.music

### ISSUE THREAD

**Issue by fayeniko** [RikkaApps/StorageRedirect-assets#1776]
## Application information - Package name: `com.google.android.music` - Version: 8.17.7736-1.K (77361) ## Reason - Path: `/storage/2360-16E2/Android/data/com.google.android.music/files/._playmusicid`

**Comment by fython** [comment]
@fayeniko In fact it didn't break verified conditions. Due to special storage root location on your device, its action was recognized as non-standard by mistake. We'll try to fix this display problem in the future version of Storage Redirect.
