### ISSUE TITLE
[New rules request][AUTO] yqtrack.app

### ISSUE THREAD

**Issue by xpduyson** [RikkaApps/StorageRedirect-assets#1777]
## Application information - Package name: `yqtrack.app` - Display name: 17TRACK - Version: 3.1.1982 (4482) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_SG - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "yqtrack.app",
  "recommended": false,
  "verified": true,
  "authors": [
    "xpduyson"
  ]
} ```

**Comment by 472714747** [comment]
## Application information - Package name: `yqtrack.app` - Display name: 17TRACK - Version: 3.1.2081 (4581) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 8.0.0 (API 26) - User language: zh_CN_#Hans - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "yqtrack.app",
  "recommended": false,
  "verified": true,
  "authors": [
    "472714747"
  ]
} ```
