### ISSUE TITLE
[New rules request][AUTO] com.bilibili.comic

### ISSUE THREAD

**Issue by david082321** [RikkaApps/StorageRedirect-assets#1809]
## Application information - Package name: `com.bilibili.comic` - Display name: 哔哩哔哩漫画 - Version: 1.2.1 (121001) ## User rules - `recommended`: Yes - `verified`: No - Reason:  ### ObserverInfo No observers. ## More information - Android version: 8.0.0 (API 26) - User language: zh_TW_#Hant - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.bilibili.comic",
  "recommended": true,
  "verified": false,
  "authors": [
    "david082321"
  ]
} ```

**Comment by YandexStudio** [comment]
## Application information - Package name: `com.bilibili.comic` - Display name: 哔哩哔哩漫画 - Version: 1.2.1 (121001) ## User rules - `recommended`: Yes - `verified`: No - Reason:  ### ObserverInfo No observers. ## More information - Android version: 8.1.0 (API 27) - User language: zh_CN - Storage Redirect app version: 1.3.3.r1408.cabb62c6-armeabi-v7a (14081) ## JSON Output ``` {
  "package": "com.bilibili.comic",
  "recommended": true,
  "verified": false,
  "authors": [
    "YandexStudio"
  ]
} ```

**Comment by Vstory** [comment]
## Application information - Package name: `com.bilibili.comic` - Display name: 哔哩哔哩漫画 - Version: 1.3.1 (131004) ## User rules - `recommended`: Yes - `verified`: No - Reason:  ### ObserverInfo No observers. ## More information - Android version: 8.1.0 (API 27) - User language: zh_CN - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.bilibili.comic",
  "recommended": true,
  "verified": false,
  "authors": [
    "Vstory"
  ]
} ```
