### ISSUE TITLE
[New rules request][AUTO] com.afollestad.mnmlscreenrecord

### ISSUE THREAD

**Issue by Love4Taylor** [RikkaApps/StorageRedirect-assets#1811]
## Application information - Package name: `com.afollestad.mnmlscreenrecord` - Display name: MNML Screen Recorder - Version: 1.0.8b (19) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.afollestad.mnmlscreenrecord",
  "recommended": false,
  "verified": true,
  "authors": [
    "Love4Taylor"
  ]
} ```

**Comment by fayeniko** [comment]
## Application information - Package name: `com.afollestad.mnmlscreenrecord` - Display name: MNML Screen Recorder - Version: 1.0.8c (20) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.afollestad.mnmlscreenrecord",
  "recommended": false,
  "verified": true,
  "authors": [
    "fayeniko"
  ]
} ```
