### ISSUE TITLE
[New rules request][AUTO] com.mixplorer.silver

### ISSUE THREAD

**Issue by lifansama** [RikkaApps/StorageRedirect-assets#1812]
## Application information - Package name: `com.mixplorer.silver` - Display name: MiXplorer - Version: 6.30.21-Silver (18122222) ## User rules - `recommended`: No - `verified`: Yes - Reason: 该应用是Mixplorer的付费版，应该被认证 ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN_#Hans - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.mixplorer.silver",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN_#Hans": "该应用是Mixplorer的付费版，应该被认证"
  },
  "authors": [
    "lifansama"
  ]
} ```

**Comment by fayeniko** [comment]
## Application information - Package name: `com.mixplorer.silver` - Display name: MiXplorer - Version: 6.30.21-Silver (18122222) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: en_US - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.mixplorer.silver",
  "recommended": false,
  "verified": true,
  "authors": [
    "fayeniko"
  ]
} ```

**Comment by ariaoftime** [comment]
## Application information - Package name: `com.mixplorer.silver` - Display name: MiXplorer - Version: 6.31.7-Silver (19010562) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN_#Hans - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.mixplorer.silver",
  "recommended": false,
  "verified": true,
  "authors": [
    "ariaoftime"
  ]
} ```

**Comment by ariaoftime** [comment]
## Application information - Package name: `com.mixplorer.silver` - Display name: MiXplorer - Version: 6.31.7-Silver (19010562) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN_#Hans - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.mixplorer.silver",
  "recommended": false,
  "verified": true,
  "authors": [
    "ariaoftime"
  ]
} ```
