### ISSUE TITLE
[Invalid verified app][AUTO] com.android.gallery3d

### ISSUE THREAD

**Issue by liuhjhj** [RikkaApps/StorageRedirect-assets#1836]
## Application information - Package name: `com.android.gallery3d` - Version: 9.0.15.302 (190015302) ## Reason - Path: `/storage/emulated/0/pictures/.Gallery2/config/gallery_garbage_album_list.xml`

**Comment by Liuhjhj** [comment]
## Application information - Package name: `com.android.gallery3d` - Version: 9.0.15.302 (190015302) ## Reason - Path: `/storage/emulated/0/pictures/.Gallery2/config/gallery_garbage_album_list.xml`

**Comment by Liuhjhj** [comment]
## Application information - Package name: `com.android.gallery3d` - Version: 9.0.15.302 (190015302) ## Reason - Path: `/storage/emulated/0/amap`

**Comment by Summerslyb** [comment]
这个你ROM的问题吧, 原生的系统图库是不会这些文件的

**Comment by Liuhjhj** [comment]
华为的emui9

**Comment by flostingapplesauce** [comment]
## Application information
- Package name: `com.android.gallery3d`
- Version: 1.1.40030 (40030)
## Reason
- Path: `/storage/3762-6630/Pictures/Screenshots/Screenshot_2019-11-19-17-08-18.png`
