### ISSUE TITLE
[New rules request][AUTO] com.mojitec.mojidict

### ISSUE THREAD

**Issue by Mirr0ch1** [RikkaApps/StorageRedirect-assets#1874]
## Application information - Package name: `com.mojitec.mojidict` - Display name: MOJi辞書 - Version: 2.7.0 (526) ## User rules - `recommended`: No - `verified`: Yes - Reason: 经过约 2 个月的全面使用，未发现坏行为。 ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.mojitec.mojidict",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN": "经过约 2 个月的全面使用，未发现坏行为。"
  },
  "authors": [
    "Mirr0ch1"
  ]
} ```

**Comment by Minyooo** [comment]
## Application information - Package name: `com.mojitec.mojidict` - Display name: MOJi辞書 - Version: 2.8.0 (532) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 9 (API 28) - User language: zh_CN - Storage Redirect app version: 1.3.3.r1408.cabb62c6-arm64-v8a (14082) ## JSON Output ``` {
  "package": "com.mojitec.mojidict",
  "recommended": false,
  "verified": true,
  "authors": [
    "Minyooo"
  ]
} ```
