### ISSUE TITLE
[Invalid verified app][AUTO] com.google.vr.vrcore

### ISSUE THREAD

**Issue by kotomei** [RikkaApps/StorageRedirect-assets#2027]
## Application information
- Package name: `com.google.vr.vrcore`
- Version: 1.19.219215888 (1607354483)
## Reason
- Path: `/storage/emulated/0/Cardboard/current_device_params`

**Comment by Oceantwo** [comment]
## Application information
- Package name: `com.google.vr.vrcore`
- Version: 1.19.219215888 (1607354483)
## Reason
- Path: `/storage/emulated/0/Cardboard`

**Comment by Misaka-11037** [comment]
## Application information
- Package name: `com.google.vr.vrcore`
- Version: 1.19.219215888 (1607354483)
## Reason
- Path: `/storage/emulated/0/Cardboard`
