### ISSUE TITLE
内容下载管理器 规则修改

### ISSUE THREAD

**Issue by efsg** [RikkaApps/StorageRedirect-assets#2032]
- 应用包名：com.android.providers.downloads
- 应用标题：内容下载管理器
- 应用版本：8.1.0

- 规则问题描述：一加氢OS安卓8.1，自带的内容下载管理器会产生/data/com.yulore.framework/sdcard/data/user/0/com.yulore.framework/
- 规则修改建议：一加用户建议开启重定向

**Comment by RikkaW** [comment]
然而并没有可靠的区分用户系统的方法

**Comment by efsg** [comment]
> 然而并没有可靠的区分用户系统的方法

只要加上建议就可以
