### ISSUE TITLE
[New rules request][AUTO] com.oneplus.filemanager

### ISSUE THREAD

**Issue by KiritoMiao** [RikkaApps/StorageRedirect-assets#204]
## Application information
 - Package name: `com.oneplus.filemanager`
 - Display name: 文件管理
 - Version: 1.7.6.180118112428.1ceb0f9 (30000500)
 ## User rules
 - `recommended`: No
 - `verified`: No
 - Reason: 这是个文件管理器
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: zh_CN
 - Storage Redirect app version: 0.12.4-beta.r514.23ddaa0 (514)
 ## JSON Output
 ```
 {
     "package": "com.oneplus.filemanager",
     "recommended": false,
     "verified": false,
     "authors": ["KiritoMiao"],
     "reason": {"zh_CN": "这是个文件管理器"},
     "observers": [
 
     ]
 }
 ```

**Comment by fython** [comment]
如果没有未经用户确认自动产生了不规范的文件夹才将 `verified` 设为 `false`。

**Comment by cqhhy2001** [comment]
## Application information
- Package name: `com.oneplus.filemanager`
- Display name: 文件管理
- Version: 1.7.7.180529203803.8397cc2 (30000600)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 请加入认证应用
### ObserverInfo
No observers.
## More information
- Android version: 8.0.0 (API 26)
- User language: en_GB
- Storage Redirect app version: 1.0.2.r1204.f2752e1e-arm64-v8a (12042)
## JSON Output
```
{
  "package": "com.oneplus.filemanager",
  "recommended": false,
  "verified": true,
  "description": {
    "en_GB": "请加入认证应用"
  },
  "authors": [
    "cqhhy2001"
  ]
}
```

**Comment by zhs852** [comment]
## Application information
- Package name: `com.oneplus.filemanager`
- Display name: 文件管理
- Version: 1.7.7.180529203803.8397cc2 (30000600)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 文件管理器，没有非标准文件夹会被生成。
### ObserverInfo
No observers.
## More information
- Android version: 8.0.0 (API 26)
- User language: zh_CN
- Storage Redirect app version: 1.0.2.r1204.f2752e1e-arm64-v8a (12042)
## JSON Output
```
{
  "package": "com.oneplus.filemanager",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN": "文件管理器，没有非标准文件夹会被生成。"
  },
  "authors": [
    "zhs852"
  ]
}
```
