### ISSUE TITLE
[New rules request][AUTO] com.meizu.net.map

### ISSUE THREAD

**Issue by Skimige** [RikkaApps/StorageRedirect-assets#206]
## Application information
 - Package name: `com.meizu.net.map`
 - Display name: 地图
 - Version: 3.1.12 (3001012)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.0 (API 24)
 - User language: zh_CN
 - Storage Redirect app version: 0.12.4-beta.r514.23ddaa0 (514)
 ## JSON Output
 ```
 {
     "package": "com.meizu.net.map",
     "recommended": true,
     "verified": false,
     "authors": ["Skimige"],
      "observers": [
 
     ]
 }
 ```

**Comment by Skimige** [comment]
忘了说，在Flyme系统上这玩意好像能绕过重定向把地图下载到 `Download/meizumap/offlinemap` 目录，留下一个忘记加 `.nomedia` 的文件夹，内含一张不像是 jpg 的 jpg

**Comment by fython** [comment]
`Download` 内算是标准文件夹，估计是通过系统的下载管理器绕过的，不重定向也应该没关系。 @RikkaW
