### ISSUE TITLE
提交新规则

### ISSUE THREAD

**Issue by lvdongyi** [RikkaApps/StorageRedirect-assets#2065]
## Basic information / 基本信息

> The following content is divided into required and optional. 
  Please delete content in parentheses after finishing the form. 
  If you know how to write rules in JSON format, recommended to submit 
  rules by pull request.
> 以下内容分为必填和选填，填写完毕好请记得删去括号内容，
  如了解如何使用 JSON 格式编写规则建议，建议使用 Pull Request 向我们提交规则。

- Application package name / 应用包名：
  
  com.iudesk.android.photo.editor
  
  
- Application title / 应用标题：
  
  照片编辑器
  
  
- Application version / 应用版本：
  
  3.9（2018-11-11）

- If application exists non-standard file writing behavior / 应用是否存在不规范的文件写入情况：
  
在/storage/emulated/0/PhotoEditor下保存图片而不是 Pictures/PhotoEditor”）
  
  
- If application works normally when redirected / 重定向后应用能否继续正常工作：
  
  是
  
  
- What should be noticed when redirected / 重定向注意事项：
  
  
## Links suggestion / 链接建议

> The following content is what information is required for submitting one link. 
  If you want to create multiple links suggestions, please copy multiple copies. 
  If you have no suggestion, please delete this section.
> 以下内容为提交一条链接需要的信息，如需创建多条链接建议，请复制多份。如果没有建议，请删除这个章节。

### Link 1 / 链接 1
/storage/emulated/0/Pictures/PhotoEditor
- What files need to be linked out / 有什么文件需要链接到外面： 
  For example, saved pictures / songs / videos / files. 例如，保存的图片/音乐/视频/文件。
  
  保存的图片
  
  
- Which folder will they be saved into / 文件将会被存在哪一个文件夹中：
  
  (Required. Relative position of folders in redirect target)
  （必填，重定向空间内的文件夹相对位置）
  重定向空间/PhotoEditor/
  
- Where should they be saved into / 文件应当被存在哪里：

  Pictures/PhotoEditor
  
- Filter regular expression / 过滤正则表达式：

  
  
- Should show a notification when created / 当创建时是否需要显示通知：

 是
  
  
- If they are multimedia files / 它们是多媒体文件吗：

  是

**Comment by fython** [comment]
@lvdongyi 我们认为一个图片编辑器保存的图片应该不需要显示下载通知，目前暂时按照 Issue 提交的表单填写为准，如有其它用户反馈再进行修改。
