### ISSUE TITLE
[New rules request][AUTO] jp.co.canon.ic.cameraconnect

### ISSUE THREAD

**Issue by Skimige** [RikkaApps/StorageRedirect-assets#208]
## Application information
 - Package name: `jp.co.canon.ic.cameraconnect`
 - Display name: Camera Connect
 - Version: 2.2.10.5 (27)
 ## User rules
 - `recommended`: No
 - `verified`: Yes
 - Reason: 会在根目录创建<相机型号>文件夹，用以储存从相机传输的照片，但是各个相机名称不同，不知道怎么重定向。
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.0 (API 24)
 - User language: zh_CN
 - Storage Redirect app version: 0.12.4-beta.r514.23ddaa0 (514)
 ## JSON Output
 ```
 {
     "package": "jp.co.canon.ic.cameraconnect",
     "recommended": false,
     "verified": true,
     "authors": ["Skimige"],
     "reason": {"zh_CN": "会在根目录创建<相机型号>文件夹，用以储存从相机传输的照片，但是各个相机名称不同，不知道怎么重定向。"},
     "observers": [
 
     ]
 }
 ```

**Comment by Skimige** [comment]
e.g. /Canon EOS 70D

**Comment by fython** [comment]
即将借助 `mount_dirs` 关键字来提供 “非重定向文件夹” 设定的建议，并在说明中引导用户自行设置重定向规则。
