### ISSUE TITLE
[New rules request][AUTO] com.bs.flt

### ISSUE THREAD

**Issue by Love4Taylor** [RikkaApps/StorageRedirect-assets#2089]
## Application information
- Package name: `com.bs.flt`
- Display name: 福建出行助手
- Version: 2.5.9.5 (65)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: en_US
- Storage Redirect app version: 1.4.6.r1491.1b0b7fdf-arm64-v8a (14912)
## JSON Output
```
{
  "package": "com.bs.flt",
  "recommended": true,
  "verified": false,
  "authors": [
    "Love4Taylor"
  ]
}
```

**Comment by mgsqz** [comment]
## Application information
- Package name: `com.bs.flt`
- Display name: 福建出行助手
- Version: 2.5.9.5 (65)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.4.7.r1500.818b49a8-arm64-v8a (15002)
## JSON Output
```
{
  "package": "com.bs.flt",
  "recommended": true,
  "verified": false,
  "authors": [
    "mgsqz"
  ]
}
```

**Comment by mgsqz** [comment]
## Application information
- Package name: `com.bs.flt`
- Display name: 福建出行助手
- Version: 2.5.9.5 (65)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.4.7.r1500.818b49a8-arm64-v8a (15002)
## JSON Output
```
{
  "package": "com.bs.flt",
  "recommended": true,
  "verified": false,
  "authors": [
    "mgsqz"
  ]
}
```
