### ISSUE TITLE
[New rules request][AUTO] com.wsw.cospa

### ISSUE THREAD

**Issue by Vstory** [RikkaApps/StorageRedirect-assets#2096]
## Application information
- Package name: `com.wsw.cospa`
- Display name: 异次元
- Version: 1.3.3 (26)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.4.6.r1491.1b0b7fdf-arm64-v8a (14912)
## JSON Output
```
{
  "package": "com.wsw.cospa",
  "recommended": true,
  "verified": false,
  "authors": [
    "Vstory"
  ]
}
```

**Comment by cjjdaq** [comment]
## Application information
- Package name: `com.wsw.cospa`
- Display name: 异次元
- Version: 1.3.4 (27)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.4.7.r1500.818b49a8-armeabi-v7a (15001)
## JSON Output
```
{
  "package": "com.wsw.cospa",
  "recommended": true,
  "verified": false,
  "authors": [
    "cjjdaq"
  ]
}
```
