### ISSUE TITLE
[Invalid verified app][AUTO] com.android.externalstorage

### ISSUE THREAD

**Issue by GSAlex** [RikkaApps/StorageRedirect-assets#2103]
## Application information
- Package name: `com.android.externalstorage`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/.transportext/amnet.0.txt`

**Comment by vikaskadyan** [comment]
## Application information
- Package name: `com.android.externalstorage`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/WallHub/Wallpapers/AutumnJungle.png`

**Comment by daiyuxiang520** [comment]
## Application information
- Package name: `com.android.externalstorage`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/test.jpg`

**Comment by flostingapplesauce** [comment]
## Application information
- Package name: `com.android.externalstorage`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/StorageRedirect_2019-11-21_13-22-07.srbackup`

**Comment by flostingapplesauce** [comment]
## Application information
- Package name: `com.android.externalstorage`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/StorageRedirect_2019-11-25_19-13-24.srbackup`
