### ISSUE TITLE
[New rules request][AUTO] com.grymala.arplan

### ISSUE THREAD

**Issue by hx64** [RikkaApps/StorageRedirect-assets#2104]
## Application information
- Package name: `com.grymala.arplan`
- Display name: ARPlan 3D
- Version: 1.5 (8)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.4.6.r1491.1b0b7fdf-armeabi-v7a (14911)
## JSON Output
```
{
  "package": "com.grymala.arplan",
  "recommended": true,
  "verified": false,
  "authors": [
    "hx64"
  ]
}
```

**Comment by TioaTyan** [comment]
## Application information
- Package name: `com.grymala.arplan`
- Display name: ARPlan 3D
- Version: 1.5 (8)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.4.7.r1500.818b49a8-arm64-v8a (15002)
## JSON Output
```
{
  "package": "com.grymala.arplan",
  "recommended": true,
  "verified": false,
  "authors": [
    "TioaTyan"
  ]
}
```
