### ISSUE TITLE
[Invalid verified app][AUTO] com.app.pornhub

### ISSUE THREAD

**Issue by GSAlex** [RikkaApps/StorageRedirect-assets#2107]
## Application information
- Package name: `com.app.pornhub`
- Version: 4.9.1 (1257)
## Reason
- Path: `/storage/emulated/0/Cardboard`

**Comment by assLlj** [comment]
## Application information
- Package name: `com.app.pornhub`
- Version: 5.1.3 (1348)
## Reason
- Path: `/storage/emulated/0/Cardboard/phone_params`

**Comment by assLlj** [comment]
## Application information - Package name: `com.app.pornhub` - Version: 5.3 (1359) ## Reason - Path: `/storage/emulated/0/Cardboard/phone_params`
