### ISSUE TITLE
[Invalid verified app][AUTO] com.android.dialer

### ISSUE THREAD

**Issue by cjjdaq** [RikkaApps/StorageRedirect-assets#2143]
## Application information
- Package name: `com.android.dialer`
- Version: 4.0.2.190114181125.d676062 (250002)
## Reason
- Path: `/storage/emulated/0/baiduTTS/bd_etts_text.dat`

**Comment by YINGZIvcvz** [comment]
## Application information
- Package name: `com.android.dialer`
- Version: 4.0.2.190114181125.d676062 (250002)
## Reason
- Path: `/storage/emulated/0/baiduTTS/bd_etts_text.dat`

**Comment by luq885** [comment]
## Application information
- Package name: `com.android.dialer`
- Version: 4.1.0 (250003)
## Reason
- Path: `/storage/emulated/0/baiduTTS/bd_etts_speech_female.dat`

**Comment by pessoalzy** [comment]
## Application information
- Package name: `com.android.dialer`
- Version: 4.0.2 (250002)
## Reason
- Path: `/storage/emulated/0/amap/openamaplocationsdk`

**Comment by pessoalzy** [comment]
## Application information
- Package name: `com.android.dialer`
- Version: 4.0.2 (250002)
## Reason
- Path: `/storage/emulated/0/amap/openamaplocationsdk`

**Comment by mchobbylong** [comment]
## Application information
- Package name: `com.android.dialer`
- Version: 4.0.2 (250002)
## Reason
- Path: `/storage/emulated/0/baiduTTS`

**Comment by jiz4oh** [comment]
## Application information
- Package name: `com.android.dialer`
- Version: 4.0.2 (250002)
## Reason
- Path: `/storage/emulated/0/baiduTTS/bd_etts_speech_female.dat`

**Comment by Ashinch** [comment]
## Application information
- Package name: `com.android.dialer`
- Version: 4.5.0 (250015)
## Reason
- Path: `/storage/emulated/0/Record/PhoneRecord/+8618577149386`
