### ISSUE TITLE
[Invalid verified app][AUTO] com.google.android.GoogleCamera

### ISSUE THREAD

**Issue by mgsqz** [RikkaApps/StorageRedirect-assets#2149]
## Application information
- Package name: `com.google.android.GoogleCamera`
- Version: 6.1.021.220943556 (45790636)
## Reason
- Path: `/storage/emulated/0/panoramas`

**Comment by mgsqz** [comment]
## Application information
- Package name: `com.google.android.GoogleCamera`
- Version: 6.1.021.220943556 (45790636)
## Reason
- Path: `/storage/emulated/0/GCam/Configs/1.xml`

**Comment by YINGZIvcvz** [comment]
## Application information
- Package name: `com.google.android.GoogleCamera`
- Version: 1_build.6.1.013.216795316 (45789781)
## Reason
- Path: `/storage/emulated/0/panoramas`

**Comment by 284354572** [comment]
## Application information
- Package name: `com.google.android.GoogleCamera`
- Version: 6.1.021.220943556 (45790636)
## Reason
- Path: `/storage/emulated/0/panoramas`

**Comment by peaceshi** [comment]
## Application information
- Package name: `com.google.android.GoogleCamera`
- Version: 6.1.021.220943556 (45790636)
## Reason
- Path: `/storage/emulated/0/panoramas`

**Comment by whc200187** [comment]
## Application information
- Package name: `com.google.android.GoogleCamera`
- Version: 4.4.020.163412804 (41174009)
## Reason
- Path: `/storage/emulated/0/panoramas`

**Comment by xseven007** [comment]
## Application information
- Package name: `com.google.android.GoogleCamera`
- Version: 2.2.1.190822.1145build-6.2.030 (49456750)
## Reason
- Path: `/storage/emulated/0/panoramas`

**Comment by WallBreakerNO4** [comment]
## Application information
- Package name: `com.google.android.GoogleCamera`
- Version: 6.3.026.265696615 (54080538)
## Reason
- Path: `/storage/emulated/0/panoramas`

**Comment by mu2er** [comment]
## Application information
- Package name: `com.google.android.GoogleCamera`
- Version: 6.2.030.244457635 (49456748)
## Reason
- Path: `/storage/emulated/0/panoramas`

**Comment by peaceshi** [comment]
## Application information - Package name: `com.google.android.GoogleCamera` - Version: 6.1.021.220943556 (45790636) ## Reason - Path: `/storage/emulated/0/GCam/Lib/ToneCurve.log`

**Comment by peaceshi** [comment]
## Application information - Package name: `com.google.android.GoogleCamera` - Version: 6.1.021.220943556 (45790636) ## Reason - Path: `/storage/emulated/0/GCam/Lib`
