### ISSUE TITLE
[New rules request][AUTO] cn.xuexi.android

### ISSUE THREAD

**Issue by lifansama** [RikkaApps/StorageRedirect-assets#2204]
## Application information
- Package name: `cn.xuexi.android`
- Display name: 学习强国
- Version: 1.2.2 (498)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.4.9.r1513.39b6cfe9-arm64-v8a (15132)
## JSON Output
```
{
  "package": "cn.xuexi.android",
  "recommended": true,
  "verified": false,
  "authors": [
    "lifansama"
  ]
}
```

**Comment by mapleshadow** [comment]
## Application information
- Package name: `cn.xuexi.android`
- Display name: 学习强国
- Version: 1.1.0 (495)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN_#Hans
- Storage Redirect app version: 1.4.9.r1513.39b6cfe9-arm64-v8a (15132)
## JSON Output
```
{
  "package": "cn.xuexi.android",
  "recommended": true,
  "verified": false,
  "authors": [
    "mapleshadow"
  ]
}
```

**Comment by lifansama** [comment]
## Application information
- Package name: `cn.xuexi.android`
- Display name: 学习强国
- Version: 1.2.2 (498)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.5.7.r1566.906f7a7c-arm64-v8a (15662)
## JSON Output
```
{
  "package": "cn.xuexi.android",
  "recommended": true,
  "verified": false,
  "authors": [
    "lifansama"
  ]
}
```
