### ISSUE TITLE
[Invalid verified app][AUTO] com.android.calendar

### ISSUE THREAD

**Issue by 597627264** [RikkaApps/StorageRedirect-assets#2215]
## Application information
- Package name: `com.android.calendar`
- Version: 10.2.6.8 (10020608)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by Ahaochan** [comment]
## Application information
- Package name: `com.android.calendar`
- Version: 10.2.6.8 (10020608)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by Ahaochan** [comment]
## Application information
- Package name: `com.android.calendar`
- Version: 10.2.6.8 (10020608)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by xiaobaitang** [comment]
## Application information
- Package name: `com.android.calendar`
- Version: 10.3.1.0 (10030100)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by RunningMelos** [comment]
## Application information
- Package name: `com.android.calendar`
- Version: 10.2.7.3 (10020703)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by xiaobaitang** [comment]
## Application information
- Package name: `com.android.calendar`
- Version: 10.3.3.0 (10030300)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by xxoolm** [comment]
## Application information
- Package name: `com.android.calendar`
- Version: 10.2.8.2 (10020802)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp.lock`

**Comment by 370958248** [comment]
## Application information
- Package name: `com.android.calendar`
- Version: 10.3.2.3 (10030203)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by cjlcdl** [comment]
## Application information
- Package name: `com.android.calendar`
- Version: 10.3.5.5 (10030505)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by 1294266616** [comment]
## Application information
- Package name: `com.android.calendar`
- Version: 11.0.0.2 (11000002)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by Ahaochan** [comment]
## Application information - Package name: `com.android.calendar` - Version: 11.0.7.8 (11000708) ## Reason - Path: `/storage/emulated/0/mipush`
