### ISSUE TITLE
[Invalid verified app][AUTO] com.linroid.zlive

### ISSUE THREAD

**Issue by wssXzzzz** [RikkaApps/StorageRedirect-assets#2239]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.0.0-beta2 (277)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190311/16.1.app.log`

**Comment by wssXzzzz** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.0.0-beta2 (277)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190312`

**Comment by david082321** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.0.1 (280)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190317/17.1.app.log`

**Comment by RioHsc** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.0.1 (280)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190320`

**Comment by nothingmore21** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.1.1 (284)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190410/18.1.app.log`

**Comment by nothingmore21** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.3.0 (291)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190422/20.1.app.log`

**Comment by peaceshi** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.3.1 (292)
## Reason
- Path: `/storage/emulated/0/tencent`

**Comment by peaceshi** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.3.1 (292)
## Reason
- Path: `/storage/emulated/0/tencent/XG`

**Comment by Woodtoleaf** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.3.1 (292)
## Reason
- Path: `/storage/emulated/0/tencent`

**Comment by noncharacter** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.3.1 (292)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190510`

**Comment by Vstory** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.3.1 (292)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190513/1.1.app.log`

**Comment by wewillchenoob** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.3.1 (292)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190517`

**Comment by wssXzzzz** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.3.1 (292)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190517/13.1.app.log`

**Comment by Altonhe** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.4.2 (303)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190603/19.1.app.log`

**Comment by hipsnafoha** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.4.3 (304)
## Reason
- Path: `/storage/emulated/0/tencent`

**Comment by abu9** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.5.2 (310)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20190721/16.1.app.log`

**Comment by abu9** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.5.2 (310)
## Reason
- Path: `/storage/emulated/0/_0ServerSendToService.txt`

**Comment by mucijinchen** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.5.2 (310)
## Reason
- Path: `/storage/emulated/0/NAD/rule/com.linroid.zlive/com.linroid.zlive.screen.host.HostActivity`

**Comment by YuiGuizhichen** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.6.0 (313)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20191015`

**Comment by pessoalzy** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: Unknown (Unknown)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20191109/14.1.app.log`

**Comment by Ashinch** [comment]
## Application information
- Package name: `com.linroid.zlive`
- Version: 4.10.0 (330)
## Reason
- Path: `/storage/emulated/0/tencent/XG/Logs/20191115`
