### ISSUE TITLE
[Invalid verified app][AUTO] com.android.systemui

### ISSUE THREAD

**Issue by IDarkBoss** [RikkaApps/StorageRedirect-assets#2315]
## Application information
- Package name: `com.android.systemui`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/3MinitBatteryIcons`

**Comment by Gemini-Shan** [comment]
## Application information
- Package name: `com.android.systemui`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/3MinitBatteryIcons`

**Comment by TTTPOB** [comment]
## Application information
- Package name: `com.android.systemui`
- Version: 20190625.0 (201906250)
## Reason
- Path: `/storage/emulated/0/MIUI`

**Comment by 0562g** [comment]
## Application information
- Package name: `com.android.systemui`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/NetworkSpeedIndicator/2019-11-17.log`
