### ISSUE TITLE
[New rules request][AUTO] net.xmind.doughnut

### ISSUE THREAD

**Issue by chisakaw** [RikkaApps/StorageRedirect-assets#2317]
## Application information
- Package name: `net.xmind.doughnut`
- Display name: XMind思维导图
- Version: 1.2.7 (23)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 7.1.2 (API 25)
- User language: zh_CN
- Storage Redirect app version: 1.5.7.r1566.906f7a7c-armeabi-v7a (15661)
## JSON Output
```
{
  "package": "net.xmind.doughnut",
  "recommended": true,
  "verified": false,
  "authors": [
    "chisakaw"
  ]
}
```

**Comment by yuukoamamiya** [comment]
## Application information
- Package name: `net.xmind.doughnut`
- Display name: XMind思维导图
- Version: 1.2.7 (23)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.5.7.r1566.906f7a7c-armeabi-v7a (15661)
## JSON Output
```
{
  "package": "net.xmind.doughnut",
  "recommended": true,
  "verified": false,
  "authors": [
    "yuukoamamiya"
  ]
}
```
