### ISSUE TITLE
[New rules request][AUTO] com.lanzou.gwa

### ISSUE THREAD

**Issue by efsg** [RikkaApps/StorageRedirect-assets#2339]
## Application information
- Package name: `com.lanzou.gwa`
- Display name: 蓝奏云
- Version: 0.0.15 (15)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.5.7.r1566.906f7a7c-arm64-v8a (15662)
## JSON Output
```
{
  "package": "com.lanzou.gwa",
  "recommended": true,
  "verified": false,
  "authors": [
    "efsg"
  ]
}
```

**Comment by 284354572** [comment]
## Application information
- Package name: `com.lanzou.gwa`
- Display name: 蓝奏云
- Version: 0.0.15 (15)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_SG_#Hans
- Storage Redirect app version: 1.5.7.r1566.906f7a7c-arm64-v8a (15662)
## JSON Output
```
{
  "package": "com.lanzou.gwa",
  "recommended": true,
  "verified": false,
  "authors": [
    "284354572"
  ]
}
```
