### ISSUE TITLE
[Invalid verified app][AUTO] com.sec.android.inputmethod

### ISSUE THREAD

**Issue by IDarkBoss** [RikkaApps/StorageRedirect-assets#2343]
## Application information
- Package name: `com.sec.android.inputmethod`
- Version: 3.3.20.16 (332016030)
## Reason
- Path: `/storage/emulated/0/sogou/corelog`

**Comment by Gemini-Shan** [comment]
## Application information
- Package name: `com.sec.android.inputmethod`
- Version: 3.3.20.34 (332034030)
## Reason
- Path: `/storage/emulated/0/sogou/corelog`
