### ISSUE TITLE
[Invalid verified app][AUTO] org.codeaurora.snapcam

### ISSUE THREAD

**Issue by monkey-sking** [RikkaApps/StorageRedirect-assets#2348]
## Application information
- Package name: `org.codeaurora.snapcam`
- Version: 1.4.032219.1950build-6.1.021 (45790636)
## Reason
- Path: `/storage/emulated/0/GCam/Configs/4.xml`

**Comment by YYDXDEKR** [comment]
## Application information
- Package name: `org.codeaurora.snapcam`
- Version: 6.1.021.220943556 (45790636)
## Reason
- Path: `/storage/emulated/0/panoramas`

**Comment by xian2xian2** [comment]
## Application information
- Package name: `org.codeaurora.snapcam`
- Version: 1.4.032219.1950build-6.1.021 (45790636)
## Reason
- Path: `/storage/emulated/0/GCam`
