### ISSUE TITLE
[New rules request][AUTO] top.linesoft.kiryuu.pandownload

### ISSUE THREAD

**Issue by shibeta** [RikkaApps/StorageRedirect-assets#2362]
## Application information
- Package name: `top.linesoft.kiryuu.pandownload`
- Display name: PanDownload
- Version: 1.0.7 (21)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.5.7.r1566.906f7a7c-arm64-v8a (15662)
## JSON Output
```
{
  "package": "top.linesoft.kiryuu.pandownload",
  "recommended": false,
  "verified": true,
  "authors": [
    "shibeta"
  ]
}
```

**Comment by wubaofeng** [comment]
## Application information
- Package name: `top.linesoft.kiryuu.pandownload`
- Display name: PanDownload
- Version: 1.0.7 (21)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.5.7.r1566.906f7a7c-arm64-v8a (15662)
## JSON Output
```
{
  "package": "top.linesoft.kiryuu.pandownload",
  "recommended": false,
  "verified": true,
  "authors": [
    "wubaofeng"
  ]
}
```
