### ISSUE TITLE
[Invalid verified app][AUTO] com.sand.airdroid

### ISSUE THREAD

**Issue by ChristopherZhao** [RikkaApps/StorageRedirect-assets#2365]
## Application information
- Package name: `com.sand.airdroid`
- Version: 4.2.2.2 (30261)
## Reason
- Path: `/storage/emulated/0/tencent/beacon/meta.dat`

**Comment by ms0ng** [comment]
## Application information
- Package name: `com.sand.airdroid`
- Version: 4.2.2.2 (30261)
## Reason
- Path: `/storage/emulated/0/tencent/beacon/meta.dat`

**Comment by gin3715** [comment]
## Application information
- Package name: `com.sand.airdroid`
- Version: 4.2.3.3 (30266)
## Reason
- Path: `/storage/emulated/0/tencent/beacon`
