### ISSUE TITLE
[Invalid verified app][AUTO] com.douban.movie

### ISSUE THREAD

**Issue by Error404HMD** [RikkaApps/StorageRedirect-assets#2379]
## Application information
- Package name: `com.douban.movie`
- Version: 4.5.0 (81)
## Reason
- Path: `/storage/emulated/0/Android/obj/.um`

**Comment by agostop** [comment]
## Application information
- Package name: `com.douban.movie`
- Version: 2.7.3 (69)
## Reason
- Path: `/storage/emulated/0/.UTSystemConfig/Global/Alvin2.xml`
