### ISSUE TITLE
[New rules request][AUTO] com.perol.asdpl.play.pixivez

### ISSUE THREAD

**Issue by HiyoriTUK** [RikkaApps/StorageRedirect-assets#2390]
## Application information
- Package name: `com.perol.asdpl.play.pixivez`
- Display name: Pix-EzViewer
- Version: 1.0.1 W (4)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
#### Directory: `PxEz`
- `description`: `saved_pictures`
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.1.r1664.a3e6ac2d-arm64-v8a (16642)
## JSON Output
```
{
  "package": "com.perol.asdpl.play.pixivez",
  "recommended": true,
  "verified": false,
  "authors": [
    "HiyoriTUK"
  ],
  "observers": [
    {
      "source": "PxEz",
      "target": "Pictures/PxEz",
      "description": "saved_pictures",
      "call_media_scan": true,
      "add_to_downloads": false,
      "allow_child": false,
      "allow_temp": false
    }
  ]
}
```

**Comment by efsg** [comment]
## Application information
- Package name: `com.perol.asdpl.play.pixivez`
- Display name: Pix-EzViewer
- Version: 1.0.1 W (4)
## User rules
- `recommended`: No
- `verified`: No
- Reason: 应用有更改保存路径的设置
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.1.r1664.a3e6ac2d-arm64-v8a (16642)
## JSON Output
```
{
  "package": "com.perol.asdpl.play.pixivez",
  "recommended": false,
  "verified": false,
  "description": {
    "zh_CN": "应用有更改保存路径的设置"
  },
  "authors": [
    "efsg"
  ]
}
```

**Comment by dCATb** [comment]
## Application information
- Package name: `com.perol.asdpl.play.pixivez`
- Display name: Pix-EzViewer
- Version: 1.0.1 W (4)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
#### Directory: `PxEz`
- `description`: `downloaded_pictures`
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.3.r1704.eb55ce07-arm64-v8a (17042)
## JSON Output
```
{
  "package": "com.perol.asdpl.play.pixivez",
  "recommended": true,
  "verified": false,
  "authors": [
    "dCATb"
  ],
  "observers": [
    {
      "source": "PxEz",
      "target": "Pictures/PxEz",
      "description": "downloaded_pictures",
      "call_media_scan": true,
      "add_to_downloads": false,
      "allow_child": true,
      "allow_temp": false
    }
  ]
}
```

**Comment by dCATb** [comment]
## Application information
- Package name: `com.perol.asdpl.play.pixivez`
- Display name: Pix-EzViewer
- Version: 1.0.1 W (4)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
#### Directory: `PxEz`
- `description`: `downloaded_pictures`
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.3.r1704.eb55ce07-arm64-v8a (17042)
## JSON Output
```
{
  "package": "com.perol.asdpl.play.pixivez",
  "recommended": true,
  "verified": false,
  "authors": [
    "dCATb"
  ],
  "observers": [
    {
      "source": "PxEz",
      "target": "Pictures/PxEz",
      "description": "downloaded_pictures",
      "call_media_scan": true,
      "add_to_downloads": false,
      "allow_child": true,
      "allow_temp": false
    }
  ]
}
```
