### ISSUE TITLE
[New rules request][AUTO] com.hypergryph.arknights

### ISSUE THREAD

**Issue by fython** [RikkaApps/StorageRedirect-assets#2391]
## Application information
- Package name: `com.hypergryph.arknights`
- Display name: 明日方舟
- Version: 0.6.66 (2)
## User rules
- `recommended`: No
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.1.r1667.4134d6fd-arm64-v8a (16672)
## JSON Output
```
{
  "package": "com.hypergryph.arknights",
  "recommended": false,
  "verified": false,
  "authors": [
    "fython"
  ]
}
```

**Comment by HaneRo** [comment]
## Application information
- Package name: `com.hypergryph.arknights`
- Display name: 明日方舟
- Version: 0.6.66 (2)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 仅在此版本（0.6.66）没有在非标准位置创建文件（夹），无法确定更新版本是否会创建
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN_#Hans
- Storage Redirect app version: 1.6.3.r1704.eb55ce07-arm64-v8a (17042)
## JSON Output
```
{
  "package": "com.hypergryph.arknights",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN_#Hans": "仅在此版本（0.6.66）没有在非标准位置创建文件（夹），无法确定更新版本是否会创建"
  },
  "authors": [
    "HaneRo"
  ]
}
```

**Comment by HaneRo** [comment]
## Application information
- Package name: `com.hypergryph.arknights`
- Display name: 明日方舟
- Version: 0.7.28 (4)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 这是一个游戏，没有访问外部储存的必要
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN_#Hans
- Storage Redirect app version: 1.6.9.r1762.9159509e-arm64-v8a (17622)
## JSON Output
```
{
  "package": "com.hypergryph.arknights",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN_#Hans": "这是一个游戏，没有访问外部储存的必要"
  },
  "authors": [
    "HaneRo"
  ]
}
```

**Comment by fython** [comment]
## Application information
- Package name: `com.hypergryph.arknights`
- Display name: 明日方舟
- Version: 0.7.27 (3)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.9.r1768.fb9b6cd6-arm64-v8a (17682)
## JSON Output
```
{
  "package": "com.hypergryph.arknights",
  "recommended": true,
  "verified": false,
  "authors": [
    "fython"
  ]
}
```
