### ISSUE TITLE
[New rules request][AUTO] gov.pianzong.androidnga

### ISSUE THREAD

**Issue by yuukoamamiya** [RikkaApps/StorageRedirect-assets#2400]
## Application information
- Package name: `gov.pianzong.androidnga`
- Display name: NGA玩家社区
- Version: 8.1.4 (80014)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.5.7.r1566.906f7a7c-armeabi-v7a (15661)
## JSON Output
```
{
  "package": "gov.pianzong.androidnga",
  "recommended": true,
  "verified": false,
  "authors": [
    "yuukoamamiya"
  ]
}
```

**Comment by wangsong0810** [comment]
## Application information
- Package name: `gov.pianzong.androidnga`
- Display name: NGA玩家社区
- Version: 7.3.1 (73001)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
#### Directory: `Pictures/nga`
- `description`: `downloaded_pictures`
## More information
- Android version: 9 (API 28)
- User language: zh_CN_#Hans
- Storage Redirect app version: 1.6.6.r1731.f59a5e23-arm64-v8a (17312)
## JSON Output
```
{
  "package": "gov.pianzong.androidnga",
  "recommended": true,
  "verified": false,
  "authors": [
    "wangsong0810"
  ],
  "observers": [
    {
      "source": "Pictures/nga",
      "target": "Pictures/NGA",
      "description": "downloaded_pictures",
      "call_media_scan": true,
      "add_to_downloads": false,
      "allow_child": false,
      "allow_temp": false
    }
  ]
}
```
