### ISSUE TITLE
[New rules request][AUTO] com.jh.onscripter

### ISSUE THREAD

**Issue by fayeniko** [RikkaApps/StorageRedirect-assets#2407]
## Application information
- Package name: `com.jh.onscripter`
- Display name: ONScripter-Jh
- Version: 0.7.6 (20181218) (10)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: en_US
- Storage Redirect app version: 1.6.3.r1704.eb55ce07-arm64-v8a (17042)
## JSON Output
```
{
  "package": "com.jh.onscripter",
  "recommended": false,
  "verified": true,
  "authors": [
    "fayeniko"
  ]
}
```

**Comment by DDoSolitary** [comment]
## Application information
- Package name: `com.jh.onscripter`
- Display name: ONScripter-Jh
- Version: 0.6 (20150820) (6)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: en_US
- Storage Redirect app version: 1.6.6.r1731.f59a5e23-arm64-v8a (17312)
## JSON Output
```
{
  "package": "com.jh.onscripter",
  "recommended": false,
  "verified": true,
  "authors": [
    "DDoSolitary"
  ]
}
```
