### ISSUE TITLE
[New rules request][AUTO] cn.nubia.browser

### ISSUE THREAD

**Issue by MasterOfStar** [RikkaApps/StorageRedirect-assets#2409]
## Application information
- Package name: `cn.nubia.browser`
- Display name: 浏览器
- Version: V5.0.2.2019012515a (15039)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 努比亚浏览器
#### Directory: `nuBrowserDownload`
- `description`: `saved_files`
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.6.3.r1704.eb55ce07-arm64-v8a (17042)
## JSON Output
```
{
  "package": "cn.nubia.browser",
  "recommended": true,
  "verified": false,
  "description": {
    "zh_CN": "努比亚浏览器"
  },
  "authors": [
    "MasterOfStar"
  ],
  "observers": [
    {
      "source": "nuBrowserDownload",
      "target": "Download/nuBrowserDownload",
      "description": "saved_files",
      "call_media_scan": true,
      "add_to_downloads": false,
      "allow_child": true,
      "allow_temp": true
    }
  ]
}
```

**Comment by benzBrake** [comment]
## Application information
- Package name: `cn.nubia.browser`
- Display name: 浏览器
- Version: V4.0.6.040416b (8182)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
#### Directory: `nuBrowserDownload`
- `description`: `saved_files`
## More information
- Android version: 7.1.1 (API 25)
- User language: zh_CN
- Storage Redirect app version: 1.6.3.r1704.eb55ce07-arm64-v8a (17042)
## JSON Output
```
{
  "package": "cn.nubia.browser",
  "recommended": true,
  "verified": false,
  "authors": [
    "benzBrake"
  ],
  "observers": [
    {
      "source": "nuBrowserDownload",
      "target": "Download/NubiaBrowser",
      "description": "saved_files",
      "call_media_scan": true,
      "add_to_downloads": false,
      "allow_child": true,
      "allow_temp": false
    }
  ]
}
```
