### ISSUE TITLE
[New rules request][AUTO] com.tencent.zb

### ISSUE THREAD

**Issue by MasterOfStar** [RikkaApps/StorageRedirect-assets#2411]
## Application information
- Package name: `com.tencent.zb`
- Display name: QQ众测
- Version: 5.9.2.1182 (1182)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.6.3.r1704.eb55ce07-arm64-v8a (17042)
## JSON Output
```
{
  "package": "com.tencent.zb",
  "recommended": true,
  "verified": false,
  "authors": [
    "MasterOfStar"
  ]
}
```

**Comment by Vstory** [comment]
## Application information
- Package name: `com.tencent.zb`
- Display name: QQ众测
- Version: 5.9.2.1182 (1182)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.6.8.r1753.be8ddccb-arm64-v8a (17532)
## JSON Output
```
{
  "package": "com.tencent.zb",
  "recommended": true,
  "verified": false,
  "authors": [
    "Vstory"
  ]
}
```
