### ISSUE TITLE
[New rules request][AUTO] cn.nubia.bbs

### ISSUE THREAD

**Issue by MasterOfStar** [RikkaApps/StorageRedirect-assets#2413]
## Application information
- Package name: `cn.nubia.bbs`
- Display name: nubia社区
- Version: 2.0.6 (116)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
#### Directory: `nubiabbs`
- `description`: `saved_files`
## More information
- Android version: 8.1.0 (API 27)
- User language: zh_CN
- Storage Redirect app version: 1.6.3.r1704.eb55ce07-arm64-v8a (17042)
## JSON Output
```
{
  "package": "cn.nubia.bbs",
  "recommended": true,
  "verified": false,
  "authors": [
    "MasterOfStar"
  ],
  "observers": [
    {
      "source": "nubiabbs",
      "target": "Pictures/nubiabbs",
      "description": "saved_files",
      "call_media_scan": true,
      "add_to_downloads": false,
      "allow_child": true,
      "allow_temp": false
    }
  ]
}
```

**Comment by benzBrake** [comment]
## Application information
- Package name: `cn.nubia.bbs`
- Display name: nubia社区
- Version: 2.0.6 (116)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 7.1.1 (API 25)
- User language: zh_CN
- Storage Redirect app version: 1.6.3.r1704.eb55ce07-arm64-v8a (17042)
## JSON Output
```
{
  "package": "cn.nubia.bbs",
  "recommended": true,
  "verified": false,
  "authors": [
    "benzBrake"
  ]
}
```
