### ISSUE TITLE
[Invalid verified app][AUTO] com.dv.adm.pay

### ISSUE THREAD

**Issue by iamdennisme** [RikkaApps/StorageRedirect-assets#2426]
## Application information
- Package name: `com.dv.adm.pay`
- Version: 7.6 (70640)
## Reason
- Path: `/storage/emulated/0/ADM`

**Comment by yigeapp** [comment]
## Application information
- Package name: `com.dv.adm.pay`
- Version: 7.6 (70640)
## Reason
- Path: `/storage/emulated/0/WechatXposed/WxSettings`
