### ISSUE TITLE
[New rules request][AUTO] com.teacapps.barcodescanner

### ISSUE THREAD

**Issue by duzhaokun123** [RikkaApps/StorageRedirect-assets#2434]
## Application information
- Package name: `com.teacapps.barcodescanner`
- Display name: QR码扫描
- Version: 2.2.3-L (106)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 7.1.2 (API 25)
- User language: zh_CN
- Storage Redirect app version: 1.6.3.r1704.eb55ce07-armeabi-v7a (17041)
## JSON Output
```
{
  "package": "com.teacapps.barcodescanner",
  "recommended": false,
  "verified": true,
  "authors": [
    "duzhaokun123"
  ]
}
```

**Comment by RyzenBlue** [comment]
## Application information
- Package name: `com.teacapps.barcodescanner`
- Display name: QR码扫描
- Version: 2.2.4-L (107)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 无需存储空间权限也可正常使用
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.9.r1762.9159509e-arm64-v8a (17622)
## JSON Output
```
{
  "package": "com.teacapps.barcodescanner",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN": "无需存储空间权限也可正常使用"
  },
  "authors": [
    "RyzenBlue"
  ]
}
```
