### ISSUE TITLE
[Invalid verified app][AUTO] com.twitter.android

### ISSUE THREAD

**Issue by KsharpMoring** [RikkaApps/StorageRedirect-assets#2441]
## Application information
- Package name: `com.twitter.android`
- Version: 7.91.1-release.46 (17911046)
## Reason
- Path: `/storage/emulated/0/WechatXposed/WxSettings`

**Comment by Maria233** [comment]
## Application information
- Package name: `com.twitter.android`
- Version: 8.9.0-release.84 (18090084)
## Reason
- Path: `/storage/emulated/0/Android/kwaiching.xml`

**Comment by Ashinch** [comment]
## Application information
- Package name: `com.twitter.android`
- Version: 8.21.0-release.00 (18210000)
## Reason
- Path: `/storage/F2F3-7863/Android/data/com.twitter.android/files`
