### ISSUE TITLE
[New rules request][AUTO] com.zzz.falsify

### ISSUE THREAD

**Issue by HuanCheng65** [RikkaApps/StorageRedirect-assets#2456]
## Application information
- Package name: `com.zzz.falsify`
- Display name: 伪贴吧
- Version: 0.4.5 (36)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 开启后下载的文件会被重定向，需要您开启“同步文件夹”规则或者调整下载路径。
#### Directory: `TB_DOWNLOAD`
- `description`: `saved_pictures`
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.5.r1724.22ba0030-armeabi-v7a (17241)
## JSON Output
```
{
  "package": "com.zzz.falsify",
  "recommended": true,
  "verified": false,
  "description": {
    "zh_CN": "开启后下载的文件会被重定向，需要您开启“同步文件夹”规则或者调整下载路径。"
  },
  "authors": [
    "HuanCheng65"
  ],
  "observers": [
    {
      "source": "TB_DOWNLOAD",
      "target": "Pictures/Falsify",
      "description": "saved_pictures",
      "call_media_scan": true,
      "add_to_downloads": true,
      "allow_child": false,
      "allow_temp": false
    }
  ]
}
```

**Comment by qiaokelidou** [comment]
## Application information
- Package name: `com.zzz.falsify`
- Display name: 伪贴吧
- Version: 0.4.5.1 (37)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 保存图片时在根目录生成tb_download文件夹，和在sdcard/android目录生成其他文件夹
### ObserverInfo
#### Directory: `TB_DOWNLOAD`
- `description`: `downloaded_pictures`
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.5.r1724.22ba0030-arm64-v8a (17242)
## JSON Output
```
{
  "package": "com.zzz.falsify",
  "recommended": true,
  "verified": false,
  "description": {
    "zh_CN": "保存图片时在根目录生成tb_download文件夹，和在sdcard/android目录生成其他文件夹"
  },
  "authors": [
    "qiaokelidou"
  ],
  "observers": [
    {
      "source": "TB_DOWNLOAD",
      "target": "Pictures/伪贴吧",
      "description": "downloaded_pictures",
      "call_media_scan": true,
      "add_to_downloads": false,
      "allow_child": true,
      "allow_temp": false
    }
  ]
}
```
