### ISSUE TITLE
[New rules request][AUTO] com.flash.download

### ISSUE THREAD

**Issue by Thundercup** [RikkaApps/StorageRedirect-assets#2459]
## Application information
- Package name: `com.flash.download`
- Display name: 闪电下载
- Version: 1.1.2 (1120)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: en_GB
- Storage Redirect app version: 1.6.5.r1724.22ba0030-arm64-v8a (17242)
## JSON Output
```
{
  "package": "com.flash.download",
  "recommended": true,
  "verified": false,
  "authors": [
    "Thundercup"
  ]
}
```

**Comment by benzBrake** [comment]
## Application information
- Package name: `com.flash.download`
- Display name: 闪电下载
- Version: 1.1.4 (1140)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 7.1.1 (API 25)
- User language: zh_CN
- Storage Redirect app version: 1.6.6.r1731.f59a5e23-arm64-v8a (17312)
## JSON Output
```
{
  "package": "com.flash.download",
  "recommended": true,
  "verified": false,
  "authors": [
    "benzBrake"
  ]
}
```

**Comment by Nonlone** [comment]
## Application information
- Package name: `com.flash.download`
- Display name: 闪电下载
- Version: 1.1.4-google (1140)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.7.r1741.5eedb815-arm64-v8a (17412)
## JSON Output
```
{
  "package": "com.flash.download",
  "recommended": true,
  "verified": false,
  "authors": [
    "Nonlone"
  ]
}
```
