### ISSUE TITLE
[Invalid verified app][AUTO] com.miui.calculator

### ISSUE THREAD

**Issue by Rick0525** [RikkaApps/StorageRedirect-assets#2486]
## Application information
- Package name: `com.miui.calculator`
- Version: 10.1.7 (138)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log/com.miui.voiceassist.mvs/2019042616.log`

**Comment by Rick0525** [comment]
## Application information
- Package name: `com.miui.calculator`
- Version: 10.1.7 (138)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log/com.miui.voiceassist.mvs/2019042616.log`

**Comment by OPTOPIA** [comment]
## Application information
- Package name: `com.miui.calculator`
- Version: 10.1.11 (200011)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log/com.miui.voiceassist.mvs`

**Comment by hipsnafoha** [comment]
## Application information
- Package name: `com.miui.calculator`
- Version: 10.1.11 (200011)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log`

**Comment by ThinDog** [comment]
## Application information
- Package name: `com.miui.calculator`
- Version: 10.1.15 (200015)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log/com.miui.voiceassist.mvs`

**Comment by chennalan** [comment]
## Application information
- Package name: `com.miui.calculator`
- Version: 10.1.3 (100003)
## Reason
- Path: `/storage/emulated/0/MIUI`
