### ISSUE TITLE
[New rules request][AUTO] com.tencent.gwgo

### ISSUE THREAD

**Issue by SkyBeautiful** [RikkaApps/StorageRedirect-assets#2491]
## Application information
- Package name: `com.tencent.gwgo`
- Display name: 一起来捉妖
- Version: 1.6.383.1 (106383)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 这是一款游戏，如果重定向，不知是否封号
### ObserverInfo
No observers.
## More information
- Android version: 9.0 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.6.r1731.f59a5e23-arm64-v8a (17312)
## JSON Output
```
{
  "package": "com.tencent.gwgo",
  "recommended": true,
  "verified": false,
  "description": {
    "zh_CN": "这是一款游戏，如果重定向，不知是否封号"
  },
  "authors": [
    "SkyBeautiful"
  ]
}
```

**Comment by aorosora** [comment]
## Application information
- Package name: `com.tencent.gwgo`
- Display name: 一起来捉妖
- Version: 1.6.383.1 (106383)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 极低概率封号，请自行斟酌！
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.6.r1731.f59a5e23-arm64-v8a (17312)
## JSON Output
```
{
  "package": "com.tencent.gwgo",
  "recommended": true,
  "verified": false,
  "description": {
    "zh_CN": "极低概率封号，请自行斟酌！"
  },
  "authors": [
    "aorosora"
  ]
}
```
