### ISSUE TITLE
[Invalid verified app][AUTO] com.miui.hybrid

### ISSUE THREAD

**Issue by SkyBeautiful** [RikkaApps/StorageRedirect-assets#2497]
## Application information
- Package name: `com.miui.hybrid`
- Version: 1.3.0.0 (10300004)
## Reason
- Path: `/storage/emulated/0/Tencent/msflogs/com`

**Comment by ilolipopi** [comment]
## Application information
- Package name: `com.miui.hybrid`
- Version: 1.4.3.1 (10430101)
## Reason
- Path: `/storage/emulated/0/.BD_SAPI_CACHE/.libbaiducuid.so`

**Comment by zym013579** [comment]
## Application information
- Package name: `com.miui.hybrid`
- Version: 1.5.0.2 (10500202)
## Reason
- Path: `/storage/emulated/0/.BD_SAPI_CACHE/.libbaiducuid.so`

**Comment by zym013579** [comment]
## Application information
- Package name: `com.miui.hybrid`
- Version: 1.5.0.2 (10500202)
## Reason
- Path: `/storage/emulated/0/backups/.SystemConfig`
