### ISSUE TITLE
[New rules request][AUTO] com.tencent.tmgp.projectg

### ISSUE THREAD

**Issue by Merlyx** [RikkaApps/StorageRedirect-assets#2533]
## Application information
- Package name: `com.tencent.tmgp.projectg`
- Display name: 孤岛行动
- Version: 1.1.4 (7915)
## User rules
- `recommended`: No
- `verified`: No
- Reason: 可能会被封号10年
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.6.r1731.f59a5e23-arm64-v8a (17312)
## JSON Output
```
{
  "package": "com.tencent.tmgp.projectg",
  "recommended": false,
  "verified": false,
  "description": {
    "zh_CN": "可能会被封号10年"
  },
  "authors": [
    "Merlyx"
  ]
}
```

**Comment by wordlesswind** [comment]
## Application information
- Package name: `com.tencent.tmgp.projectg`
- Display name: [体验服]和平精英
- Version: 1.1.14 (7970)
## User rules
- `recommended`: No
- `verified`: No
- Reason: 《绝地求生：刺激战场》的“换壳”版本，根据《绝地求生：刺激战场》的规则，开启重定向将导致帐号被封停。
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.7.r1741.5eedb815-arm64-v8a (17412)
## JSON Output
```
{
  "package": "com.tencent.tmgp.projectg",
  "recommended": false,
  "verified": false,
  "description": {
    "zh_CN": "《绝地求生：刺激战场》的“换壳”版本，根据《绝地求生：刺激战场》的规则，开启重定向将导致帐号被封停。"
  },
  "authors": [
    "wordlesswind"
  ]
}
```
