### ISSUE TITLE
[New rules request][AUTO] com.chenupt.memory

### ISSUE THREAD

**Issue by RioHsc** [RikkaApps/StorageRedirect-assets#2569]
## Application information
- Package name: `com.chenupt.memory`
- Display name: 日子
- Version: 1.14.2 (384)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: en_US
- Storage Redirect app version: 1.6.7.r1741.5eedb815-arm64-v8a (17412)
## JSON Output
```
{
  "package": "com.chenupt.memory",
  "recommended": false,
  "verified": true,
  "authors": [
    "RioHsc"
  ]
}
```

**Comment by zack66** [comment]
## Application information
- Package name: `com.chenupt.memory`
- Display name: 日子
- Version: 1.14.2 (384)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.9.r1762.9159509e-arm64-v8a (17622)
## JSON Output
```
{
  "package": "com.chenupt.memory",
  "recommended": false,
  "verified": true,
  "authors": [
    "zack66"
  ]
}
```
