### ISSUE TITLE
[Invalid verified app][AUTO] com.speedsoftware.rootexplorer

### ISSUE THREAD

**Issue by Gemini-Shan** [RikkaApps/StorageRedirect-assets#2589]
## Application information
- Package name: `com.speedsoftware.rootexplorer`
- Version: 4.4.2 (999495)
## Reason
- Path: `/storage/emulated/0/NAD/rule/com.speedsoftware.rootexplorer/com.speedsoftware.rootexplorer.RootExplorer`

**Comment by Gemini-Shan** [comment]
## Application information
- Package name: `com.speedsoftware.rootexplorer`
- Version: 4.4.2 (999495)
## Reason
- Path: `/storage/emulated/0/NAD/rule/com.speedsoftware.rootexplorer/com.speedsoftware.rootexplorer.RootExplorer`

**Comment by Gemini-Shan** [comment]
## Application information
- Package name: `com.speedsoftware.rootexplorer`
- Version: 4.4.2 (999495)
## Reason
- Path: `/storage/emulated/0/NAD/rule/com.speedsoftware.rootexplorer/com.speedsoftware.rootexplorer.RootExplorer`

**Comment by hao1196561270** [comment]
## Application information
- Package name: `com.speedsoftware.rootexplorer`
- Version: 4.3 (145)
## Reason
- Path: `/storage/emulated/0/.dlprovider/setting.cfg`

**Comment by wqk317** [comment]
## Application information
- Package name: `com.speedsoftware.rootexplorer`
- Version: 4.9.5 (999495)
## Reason
- Path: `/storage/emulated/0/backups`

**Comment by wqk317** [comment]
## Application information
- Package name: `com.speedsoftware.rootexplorer`
- Version: 4.9.5 (999495)
## Reason
- Path: `/storage/emulated/0/backups/system/.timestamp`

**Comment by KkkeJ** [comment]
## Application information
- Package name: `com.speedsoftware.rootexplorer`
- Version: 4.5.2 (167)
## Reason
- Path: `/storage/emulated/0/SpeedSoftware/Extracted`
