### ISSUE TITLE
[New rules request][AUTO] com.baidu.lbs.waimai

### ISSUE THREAD

**Issue by geng9301** [RikkaApps/StorageRedirect-assets#259]
## Application information
 - Package name: `com.baidu.lbs.waimai`
 - Display name: 百度外卖
 - Version: 4.15.0 (124)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 #### Directory: `BaiduWM/file`
 - `description`: `downloaded_files`

 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: zh_CN_#Hans
 - Storage Redirect app version: 0.12.11-beta.r554.0e342a9 (554)
 ## JSON Output
 ```
 {
     "package": "com.baidu.lbs.waimai",
     "recommended": true,
     "verified": false,
     "authors": ["geng9301"],
      "observers": [
         {
             "description": "downloaded_files",
             "source": "BaiduWM/file"
         }
     ]
 }
 ```

**Comment by fython** [comment]
@geng9301 百度外卖会在 `BaiduWM/file` 存什么文件？

**Comment by sharp-tasting** [comment]
我猜应该把 `observers` 清空掉(
这种软件不可能留需要备份的文件的🤣
