### ISSUE TITLE
[New rules request][AUTO] wangdaye.com.geometricweather

### ISSUE THREAD

**Issue by Skimige** [RikkaApps/StorageRedirect-assets#2595]
## Application information
- Package name: `wangdaye.com.geometricweather`
- Display name: Geometric Weather
- Version: 2.253 (2253)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.0.0 (API 26)
- User language: zh_CN
- Storage Redirect app version: 1.6.7.r1741.5eedb815-arm64-v8a (17412)
## JSON Output
```
{
  "package": "wangdaye.com.geometricweather",
  "recommended": true,
  "verified": false,
  "authors": [
    "Skimige"
  ]
}
```

**Comment by YYDXDEKR** [comment]
## Application information
- Package name: `wangdaye.com.geometricweather`
- Display name: Geometric Weather
- Version: 2.253 (2253)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 当应用内定位方式选择百度定位时会在储存目录建立baidu文件夹
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.9.r1762.9159509e-arm64-v8a (17622)
## JSON Output
```
{
  "package": "wangdaye.com.geometricweather",
  "recommended": true,
  "verified": false,
  "description": {
    "zh_CN": "当应用内定位方式选择百度定位时会在储存目录建立baidu文件夹"
  },
  "authors": [
    "YYDXDEKR"
  ]
}
```
