### ISSUE TITLE
[New rules request][AUTO] com.bilibili.star.bili

### ISSUE THREAD

**Issue by fython** [RikkaApps/StorageRedirect-assets#2601]
## Application information
- Package name: `com.bilibili.star.bili`
- Display name: BanG Dream!
- Version: 1.15.1 (5)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.6.3.r1714.c092590d-arm64-v8a (17142)
## JSON Output
```
{
  "package": "com.bilibili.star.bili",
  "recommended": true,
  "verified": false,
  "authors": [
    "fython"
  ]
}
```

**Comment by ffexis** [comment]
## Application information
- Package name: `com.bilibili.star.bili`
- Display name: BanG Dream!
- Version: 1.15.12 (14)
## User rules
- `recommended`: Yes
- `verified`: No
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 8.0.0 (API 26)
- User language: zh_CN
- Storage Redirect app version: 1.6.9.r1762.9159509e-arm64-v8a (17622)
## JSON Output
```
{
  "package": "com.bilibili.star.bili",
  "recommended": true,
  "verified": false,
  "authors": [
    "ffexis"
  ]
}
```
