### ISSUE TITLE
[Invalid verified app][AUTO] ml.cerasus.pics

### ISSUE THREAD

**Issue by asahi952** [RikkaApps/StorageRedirect-assets#2603]
## Application information
- Package name: `ml.cerasus.pics`
- Version: 3.0.3 (190508)
## Reason
- Path: `/storage/emulated/0/AndroLua`

**Comment by KyokuAsahi** [comment]
## Application information
- Package name: `ml.cerasus.pics`
- Version: 3.0.3 (190508)
## Reason
- Path: `/storage/emulated/0/AndroLua`

**Comment by Xlovebsy** [comment]
## Application information
- Package name: `ml.cerasus.pics`
- Version: 3.1.6 (190602)
## Reason
- Path: `/storage/emulated/0/AndroLua`
