### ISSUE TITLE
[Invalid verified app][AUTO] wangdaye.com.geometricweather

### ISSUE THREAD

**Issue by Ryandan** [RikkaApps/StorageRedirect-assets#2658]
## Application information
- Package name: `wangdaye.com.geometricweather`
- Version: 2.253 (2253)
## Reason
- Path: `/storage/emulated/0/.UTSystemConfig/Global/Alvin2.xml`

**Comment by Cy324** [comment]
## Application information
- Package name: `wangdaye.com.geometricweather`
- Version: 2.302 (2302)
## Reason
- Path: `/storage/emulated/0/baidu/tempdata/lcvif.dat`

**Comment by Cy324** [comment]
## Application information
- Package name: `wangdaye.com.geometricweather`
- Version: 2.302 (2302)
## Reason
- Path: `/storage/emulated/0/baidu/tempdata/lcvif.dat`
