### ISSUE TITLE
[Invalid verified app][AUTO] com.sec.android.app.sbrowser

### ISSUE THREAD

**Issue by Gemini-Shan** [RikkaApps/StorageRedirect-assets#2686]
## Application information
- Package name: `com.sec.android.app.sbrowser`
- Version: 9.3.00.15 (930015100)
## Reason
- Path: `/storage/emulated/0/QQBrowser/.Application/com.sec.android.app.sbrowser.id`

**Comment by AlexanderWolfZhang** [comment]
## Application information
- Package name: `com.sec.android.app.sbrowser`
- Version: 9.4.00.45 (940045100)
## Reason
- Path: `/storage/emulated/0/QQBrowser/.Application/com.sec.android.app.sbrowser.idx`

**Comment by Gemini-Shan** [comment]
## Application information
- Package name: `com.sec.android.app.sbrowser`
- Version: 10.1.01.3 (1010103502)
## Reason
- Path: `/storage/emulated/0/QQBrowser/.Application/com.sec.android.app.sbrowser.id`
