### ISSUE TITLE
[New rules request][AUTO] com.ideal.flyerteacafes

### ISSUE THREAD

**Issue by my971208** [RikkaApps/StorageRedirect-assets#269]
## Application information
 - Package name: `com.ideal.flyerteacafes`
 - Display name: 飞客茶馆
 - Version: 6.17.0 (51)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 #### Directory: `Flyertea/cacheImage`
 - `description`: `downloaded_pictures`
#### Directory: `Flyertea/cacheData`
 - `description`: `缓存数据`
#### Directory: `Flyertea/cacheVideo`
 - `description`: `downloaded_videos`
#### Directory: `backup/com.ideal.flyerteacafes`
 - `description`: `app_backup`
#### Directory: `Flyertea/飞客茶馆`
 - `description`: `saved_files`

 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: zh_CN_#Hans
 - Storage Redirect app version: 0.12.11-beta.r554.0e342a9 (554)
 ## JSON Output
 ```
 {
     "package": "com.ideal.flyerteacafes",
     "recommended": true,
     "verified": false,
     "authors": ["my971208"],
      "observers": [
         {
             "description": "downloaded_pictures",
             "source": "Flyertea/cacheImage"
         },
         {
             "description": "缓存数据",
             "source": "Flyertea/cacheData"
         },
         {
             "description": "downloaded_videos",
             "source": "Flyertea/cacheVideo"
         },
         {
             "description": "app_backup",
             "source": "backup/com.ideal.flyerteacafes"
         },
         {
             "description": "saved_files",
             "source": "Flyertea/飞客茶馆"
         }
     ]
 }
 ```

**Comment by fython** [comment]
这三个文件夹里的文件不是用户主动保存的吧：

- `Flyertea/cacheImage`
- `Flyertea/cacheData`
- `Flyertea/cacheVideo`

**Comment by fython** [comment]
提交者未解疑，暂时关闭。
