### ISSUE TITLE
[New rules request][AUTO] me.zhanghai.android.files

### ISSUE THREAD

**Issue by fayeniko** [RikkaApps/StorageRedirect-assets#2712]
## Application information
- Package name: `me.zhanghai.android.files`
- Display name: Material Files
- Version: 1.0.0-beta.1 (2)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: en_US
- Storage Redirect app version: 1.6.9.r1762.9159509e-arm64-v8a (17622)
## JSON Output
```
{
  "package": "me.zhanghai.android.files",
  "recommended": false,
  "verified": true,
  "authors": [
    "fayeniko"
  ]
}
```

**Comment by Keriteal** [comment]
## Application information
- Package name: `me.zhanghai.android.files`
- Display name: 质感文件
- Version: 1.0.0-beta.4 (5)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "me.zhanghai.android.files",
  "recommend": false,
  "verified": true,
  "authors": [
    "Keriteal"
  ]
}
```
