### ISSUE TITLE
[Invalid verified app][AUTO] com.solohsu.android.edxp.manager

### ISSUE THREAD

**Issue by aichiyu** [RikkaApps/StorageRedirect-assets#2750]
## Application information
- Package name: `com.solohsu.android.edxp.manager`
- Version: 2.2.4 (10)
## Reason
- Path: `/storage/emulated/0/XposedInstaller/modules/WeiboXposed.apk`

**Comment by Cy324** [comment]
## Application information
- Package name: `com.solohsu.android.edxp.manager`
- Version: 2.2.4 (10)
## Reason
- Path: `/storage/emulated/0/NAD/rule/com.solohsu.android.edxp.manager`

**Comment by Cy324** [comment]
## Application information
- Package name: `com.solohsu.android.edxp.manager`
- Version: 2.2.4 (10)
## Reason
- Path: `/storage/emulated/0/NAD`
