### ISSUE TITLE
[Invalid verified app][AUTO] com.nianticlabs.pokemongo

### ISSUE THREAD

**Issue by wroogle** [RikkaApps/StorageRedirect-assets#2770]
## Application information
- Package name: `com.nianticlabs.pokemongo`
- Version: 0.145.1 (2019060301)
## Reason
- Path: `/storage/emulated/0/.backups/com.nianticlabs.pokemongo`

**Comment by Skimige** [comment]
## Application information
- Package name: `com.nianticlabs.pokemongo`
- Version: 0.147.1 (2019062400)
## Reason
- Path: `/storage/emulated/0/.backups/com.nianticlabs.pokemongo`
