### ISSUE TITLE
[Invalid verified app][AUTO] com.sspai.cuto.android

### ISSUE THREAD

**Issue by Cy324** [RikkaApps/StorageRedirect-assets#2775]
## Application information
- Package name: `com.sspai.cuto.android`
- Version: 1.6.4 (43)
## Reason
- Path: `/storage/emulated/0/logger/logs_0.txt`

**Comment by Cy324** [comment]
## Application information
- Package name: `com.sspai.cuto.android`
- Version: 1.6.4 (43)
## Reason
- Path: `/storage/emulated/0/logger/logs_0.txt`

**Comment by greatye** [comment]
## Application information
- Package name: `com.sspai.cuto.android`
- Version: 1.6.4 (43)
## Reason
- Path: `/storage/emulated/0/logger/logs_0.txt`
