### ISSUE TITLE
[New rules request][AUTO] net.oneplus.commonlogtool

### ISSUE THREAD

**Issue by Mister-Hope** [RikkaApps/StorageRedirect-assets#2810]
## Application information
- Package name: `net.oneplus.commonlogtool`
- Display name: Common Log Tool
- Version: 1.3.0.190319182006.50d8c43 (400)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "net.oneplus.commonlogtool",
  "recommend": false,
  "verified": true,
  "authors": [
    "GodofHope"
  ]
}
```

**Comment by GodofHope** [comment]
## Application information
- Package name: `net.oneplus.commonlogtool`
- Display name: Common Log Tool
- Version: 1.3.0.190319182006.50d8c43 (400)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "net.oneplus.commonlogtool",
  "recommend": false,
  "verified": true,
  "authors": [
    "GodofHope"
  ]
}
```

**Comment by GodofHope** [comment]
Why isn't it accepted？

**Comment by Mister-Hope** [comment]
Hey?
