### ISSUE TITLE
[New rules request][AUTO] com.oneplus.brickmode

### ISSUE THREAD

**Issue by Mister-Hope** [RikkaApps/StorageRedirect-assets#2811]
## Application information
- Package name: `com.oneplus.brickmode`
- Display name: 禅定模式
- Version: 1.1.0 (10)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "com.oneplus.brickmode",
  "recommend": false,
  "verified": true,
  "authors": [
    "GodofHope"
  ]
}
```

**Comment by Asstiff** [comment]
## Application information
- Package name: `com.oneplus.brickmode`
- Display name: 禅定模式
- Version: 1.1.0 (10)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "com.oneplus.brickmode",
  "recommend": false,
  "verified": true,
  "authors": [
    "Asstiff"
  ]
}
```

**Comment by GodofHope** [comment]
## Application information
- Package name: `com.oneplus.brickmode`
- Display name: 禅定模式
- Version: 1.1.0 (10)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "com.oneplus.brickmode",
  "recommend": false,
  "verified": true,
  "authors": [
    "GodofHope"
  ]
}
```

**Comment by GodofHope** [comment]
Why isn't it accepted？

**Comment by Mister-Hope** [comment]
## Application information
- Package name: `com.oneplus.brickmode`
- Display name: 禅定模式
- Version: 1.3.0.190829182129.a41f26a (120)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 10 (API 29)
- User language: zh_CN
- Storage Redirect app version: 1.9.1.r1974.0521e9fe-arm64-v8a (19742)
## JSON Output
```
{
  "package": "com.oneplus.brickmode",
  "recommend": false,
  "verified": true,
  "authors": [
    "Mister-Hope"
  ]
}
```
