### ISSUE TITLE
[New rules request][AUTO] com.oneplus.sound.tuner

### ISSUE THREAD

**Issue by Mister-Hope** [RikkaApps/StorageRedirect-assets#2812]
## Application information
- Package name: `com.oneplus.sound.tuner`
- Display name: 杜比全景声
- Version: 1.0.2 (1)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "com.oneplus.sound.tuner",
  "recommend": false,
  "verified": true,
  "authors": [
    "GodofHope"
  ]
}
```

**Comment by Asstiff** [comment]
## Application information
- Package name: `com.oneplus.sound.tuner`
- Display name: 杜比全景声
- Version: 1.0.2 (1)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "com.oneplus.sound.tuner",
  "recommend": false,
  "verified": true,
  "authors": [
    "Asstiff"
  ]
}
```

**Comment by ChemCodex** [comment]
## Application information
- Package name: `com.oneplus.sound.tuner`
- Display name: 杜比全景聲
- Version: 1.1.0 (50)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_TW_#Hant
- Storage Redirect app version: 1.8.0.r1894.c3c414a2-arm64-v8a (18942)
## JSON Output
```
{
  "package": "com.oneplus.sound.tuner",
  "recommend": false,
  "verified": true,
  "authors": [
    "ChemCodex"
  ]
}
```

**Comment by Mister-Hope** [comment]
## Application information
- Package name: `com.oneplus.sound.tuner`
- Display name: 杜比全景声
- Version: 2.0.0 (52)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 10 (API 29)
- User language: zh_CN
- Storage Redirect app version: 1.9.1.r1974.0521e9fe-arm64-v8a (19742)
## JSON Output
```
{
  "package": "com.oneplus.sound.tuner",
  "recommend": false,
  "verified": true,
  "authors": [
    "Mister-Hope"
  ]
}
```

**Comment by Mister-Hope** [comment]
Could you accept it？
