### ISSUE TITLE
[New rules request][AUTO] com.oneplus.screenrecord

### ISSUE THREAD

**Issue by Mister-Hope** [RikkaApps/StorageRedirect-assets#2813]
## Application information
- Package name: `com.oneplus.screenrecord`
- Display name: 屏幕录制
- Version: 2.1.0.190523191303.7f5ffb4 (100)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "com.oneplus.screenrecord",
  "recommend": false,
  "verified": true,
  "authors": [
    "GodofHope"
  ]
}
```

**Comment by zack66** [comment]
## Application information
- Package name: `com.oneplus.screenrecord`
- Display name: 屏幕录制
- Version: 2.1.0.190523182911.5413b83 (100)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "com.oneplus.screenrecord",
  "recommend": false,
  "verified": true,
  "authors": [
    "zack66"
  ]
}
```

**Comment by GodofHope** [comment]
## Application information
- Package name: `com.oneplus.screenrecord`
- Display name: 屏幕录制
- Version: 2.1.0.190523191303.7f5ffb4 (100)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "com.oneplus.screenrecord",
  "recommend": false,
  "verified": true,
  "authors": [
    "GodofHope"
  ]
}
```

**Comment by GodofHope** [comment]
Why isn't it accepted？
