### ISSUE TITLE
[Invalid verified app][AUTO] com.android.deskclock

### ISSUE THREAD

**Issue by Doubi250** [RikkaApps/StorageRedirect-assets#2878]
## Application information
- Package name: `com.android.deskclock`
- Version: 9.2.19.0 (9201900)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log/com.android.deskclock/android.android.deskclock.log`

**Comment by YandexStudio** [comment]
MIUI的锅，AOSP不背

**Comment by xuepiaowei** [comment]
## Application information
- Package name: `com.android.deskclock`
- Version: 9.2.19.0 (9201900)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log/com.android.deskclock/android.android.deskclock.log`

**Comment by Carlos920** [comment]
## Application information
- Package name: `com.android.deskclock`
- Version: 9.2.20.0 (9202000)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log/com.android.deskclock/android.android.deskclock.log`

**Comment by sakuraSK** [comment]
## Application information
- Package name: `com.android.deskclock`
- Version: 9.2.20.0 (9202000)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log/com.android.deskclock/android.android.deskclock.log`

**Comment by xuepiaowei** [comment]
## Application information
- Package name: `com.android.deskclock`
- Version: 9.2.20.0 (9202000)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log/com.android.deskclock/android.android.deskclock.log`

**Comment by CBGan** [comment]
## Application information
- Package name: `com.android.deskclock`
- Version: 9.2.20.0 (9202000)
## Reason
- Path: `/storage/emulated/0/MIUI/debug_log/com.android.deskclock/android.android.deskclock.log`
