### ISSUE TITLE
[Invalid verified app][AUTO] com.nianticproject.ingress

### ISSUE THREAD

**Issue by Skimige** [RikkaApps/StorageRedirect-assets#2916]
## Application information
- Package name: `com.nianticproject.ingress`
- Version: 2.26.2 (2026002)
## Reason
- Path: `/storage/emulated/0/.backups/com.nianticproject.ingress/helpshift/databases/__hs__backup_dao_storage`

**Comment by outloudvi** [comment]
Can confirm it at Ingress Prime 2.27.2. Moved that directory away, opened and did a hack in Ingress Prime then the file appeared again.

cc @simonsmh Could you reproduce that?

**Comment by simonsmh** [comment]
@outloudvi I'm not using Storage Redirects currently, so I could not reproduce now and offer a fix. Sorry about that.
Also, the ingress prime is not the same app what you are talking about, this app is now called _Scanner [REDACTED]_.
Related file: https://github.com/RikkaApps/StorageRedirect-assets/blob/master/rules/apps/com.nianticproject.ingress.json

**Comment by outloudvi** [comment]
@simonsmh com.nianticproject.ingress is Ingress (Prime) now.
Scanner [REDACTED] has the package name of com.nianticlabs.ingress.prime.qa.

GP link:
- https://play.google.com/store/apps/details?id=com.nianticproject.ingress
- https://play.google.com/store/apps/details?id=com.nianticlabs.ingress.prime.qa

**Comment by TioaTyan** [comment]
## Application information
- Package name: `com.nianticproject.ingress`
- Version: 2.27.3 (2027003)
## Reason
- Path: `/storage/emulated/0/.backups/com.nianticproject.ingress/helpshift/databases/__hs__backup_dao_storage`
