### ISSUE TITLE
[Invalid verified app][AUTO] com.mojitec.mojidict

### ISSUE THREAD

**Issue by cheeserick** [RikkaApps/StorageRedirect-assets#2939]
## Application information
- Package name: `com.mojitec.mojidict`
- Version: 3.1.1 (552)
## Reason
- Path: `/storage/emulated/0/OSSLog/logs.csv`

**Comment by kuondayo** [comment]
## Application information
- Package name: `com.mojitec.mojidict`
- Version: 3.1.2 (558)
## Reason
- Path: `/storage/emulated/0/OSSLog`

**Comment by kuondayo** [comment]
## Application information
- Package name: `com.mojitec.mojidict`
- Version: 3.1.2 (558)
## Reason
- Path: `/storage/emulated/0/OSSLog/logs.csv`

**Comment by kuondayo** [comment]
## Application information
- Package name: `com.mojitec.mojidict`
- Version: 3.1.2 (558)
## Reason
- Path: `/storage/emulated/0/OSSLog/logs.csv`
