### ISSUE TITLE
[Invalid verified app][AUTO] gov.anzong.androidnga

### ISSUE THREAD

**Issue by zzzop** [RikkaApps/StorageRedirect-assets#2944]
## Application information
- Package name: `gov.anzong.androidnga`
- Version: 2.1.16 (2116)
## Reason
- Path: `/storage/emulated/0/.awp/64/awp_core.apk`

**Comment by KuroKumaKai** [comment]
## Application information
- Package name: `gov.anzong.androidnga`
- Version: 2.1.19 (2119)
## Reason
- Path: `/storage/emulated/0/NAD/rule/gov.anzong.androidnga/gov.anzong.androidnga.activity.MainActivity`
