### ISSUE TITLE
[Invalid verified app][AUTO] com.miui.guardprovider

### ISSUE THREAD

**Issue by StageGuard** [RikkaApps/StorageRedirect-assets#2957]
## Application information
- Package name: `com.miui.guardprovider`
- Version: 1.0.5 (105)
## Reason
- Path: `/storage/emulated/0/.turing.dat`

**Comment by StageGuard** [comment]
## Application information
- Package name: `com.miui.guardprovider`
- Version: 1.0.5 (105)
## Reason
- Path: `/storage/emulated/0/.turing.dat`

**Comment by RunningMelos** [comment]
## Application information
- Package name: `com.miui.guardprovider`
- Version: 1.0.8 (108)
## Reason
- Path: `/storage/emulated/0/.turing.dat`

**Comment by sakuraSK** [comment]
## Application information
- Package name: `com.miui.guardprovider`
- Version: 1.0.8 (108)
## Reason
- Path: `/storage/emulated/0/Android/.iacovnfld.`

**Comment by neoblackxt** [comment]
## Application information
- Package name: `com.miui.guardprovider`
- Version: 1.0.8 (108)
## Reason
- Path: `/storage/emulated/0/Android/.iacovnfld.`

**Comment by qwer233qq** [comment]
## Application information
- Package name: `com.miui.guardprovider`
- Version: 1.0.8 (108)
## Reason
- Path: `/storage/emulated/0/Android/.iacovnfld.`

**Comment by xuepiaowei** [comment]
## Application information
- Package name: `com.miui.guardprovider`
- Version: 1.0.8 (108)
## Reason
- Path: `/storage/emulated/0/Android/.iacovnfld.`

**Comment by iovw** [comment]
## Application information
- Package name: `com.miui.guardprovider`
- Version: 1.0.8 (108)
## Reason
- Path: `/storage/emulated/0/Android/.iacovnfld.`

**Comment by H-olxx** [comment]
## Application information - Package name: `com.miui.guardprovider` - Version: 1.0.8 (108) ## Reason - Path: `/storage/emulated/0/Android/.iacovnfld.`

**Comment by H-olxx** [comment]
## Application information - Package name: `com.miui.guardprovider` - Version: 1.0.8 (108) ## Reason - Path: `/storage/emulated/0/Android/.iacovnfld.`
