### ISSUE TITLE
[New rules request][AUTO] com.google.android.apps.photosgo

### ISSUE THREAD

**Issue by LufsX** [RikkaApps/StorageRedirect-assets#2972]
## Application information
- Package name: `com.google.android.apps.photosgo`
- Display name: 图库精简版
- Version: 1.0.1.258899354 release (205954)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: Google 推出的 图库精简版
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.3.r1839.97931d58-arm64-v8a (18392)
## JSON Output
```
{
  "package": "com.google.android.apps.photosgo",
  "recommend": false,
  "verified": true,
  "description": {
    "zh_CN": "Google 推出的 图库精简版"
  },
  "authors": [
    "LufsX"
  ]
}
```

**Comment by xhn16729** [comment]
## Application information
- Package name: `com.google.android.apps.photosgo`
- Display name: Gallery Go
- Version: 1.0.1.258899354 release (205954)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: en_US
- Storage Redirect app version: 1.7.5.r1857.2b69cd20-arm64-v8a (18572)
## JSON Output
```
{
  "package": "com.google.android.apps.photosgo",
  "recommend": false,
  "verified": true,
  "authors": [
    "xhn16729"
  ]
}
```
