### ISSUE TITLE
[New rules request][AUTO] com.aefyr.sai

### ISSUE THREAD

**Issue by lifansama** [RikkaApps/StorageRedirect-assets#2973]
## Application information
- Package name: `com.aefyr.sai`
- Display name: SAI
- Version: 1.27 (28)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.7.2.r1830.508cf617-arm64-v8a (18302)
## JSON Output
```
{
  "package": "com.aefyr.sai",
  "recommend": false,
  "verified": true,
  "authors": [
    "lifansama"
  ]
}
```

**Comment by YandexStudio** [comment]
## Application information
- Package name: `com.aefyr.sai`
- Display name: SAI
- Version: 2.5 (35)
## User rules
- `recommended`: {recommended}
- `verified`: no
- Reason: 
### ObserverInfo
#### Directory: `SAI`
- `description`: `app_backup`
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.9.1.r1974.0521e9fe-arm64-v8a (19742)
## JSON Output
```
{
  "package": "com.aefyr.sai",
  "recommend": true,
  "verified": false,
  "authors": [
    "YandexStudio"
  ],
  "observers": [
    {
      "source": "SAI",
      "target": "Documents/SAI",
      "description": "app_backup",
      "call_media_scan": false,
      "add_to_downloads": true,
      "allow_child": true,
      "allow_temp": false
    }
  ]
}
```
