### ISSUE TITLE
[Invalid verified app][AUTO] com.caij.see

### ISSUE THREAD

**Issue by Frozty4628** [RikkaApps/StorageRedirect-assets#3021]
## Application information
- Package name: `com.caij.see`
- Version: 1.4.4.1 (60)
## Reason
- Path: `/storage/emulated/0/amap/openamaplocationsdk/1565613336292.db`

**Comment by Frozty4628** [comment]
## Application information
- Package name: `com.caij.see`
- Version: 1.4.4.1 (60)
## Reason
- Path: `/storage/emulated/0/Tencent/msflogs/com/tencent/mobileqq/com.tencent.mobileqq_connectSdk.19.08.19.02.log`

**Comment by ForInfinity** [comment]
## Application information
- Package name: `com.caij.see`
- Version: 1.4.6.3 (69)
## Reason
- Path: `/storage/emulated/0/amap/openamaplocationsdk/1568257589219.db`
