### ISSUE TITLE
[Invalid verified app][AUTO] com.android.thememanager

### ISSUE THREAD

**Issue by xuepiaowei** [RikkaApps/StorageRedirect-assets#3093]
## Application information
- Package name: `com.android.thememanager`
- Version: 1.6.2.0 (620)
## Reason
- Path: `/storage/emulated/0/MIUI/theme/.data/meta/contact/cbb0dece-ecad-440a-8053-73fee3e51bbe.mrm`

**Comment by iovw** [comment]
## Application information
- Package name: `com.android.thememanager`
- Version: 1.6.3.1 (631)
## Reason
- Path: `/storage/emulated/0/MIUI/theme/.data/content/theme/6673cc66-a73c-4d3e-b5a2-0a4d1515b831.mrc`

**Comment by 1294266616** [comment]
## Application information
- Package name: `com.android.thememanager`
- Version: 1.6.8.2 (682)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`

**Comment by fm922** [comment]
## Application information
- Package name: `com.android.thememanager`
- Version: 1.6.9.4 (694)
## Reason
- Path: `/storage/emulated/0/mipush/lcfp`
