### ISSUE TITLE
[Invalid verified app][AUTO] com.oneplus.cloud

### ISSUE THREAD

**Issue by iamdennisme** [RikkaApps/StorageRedirect-assets#3100]
## Application information
- Package name: `com.oneplus.cloud`
- Version: 3.2.0 (400)
## Reason
- Path: `/storage/emulated/0/OSSLog/logs.csv`

**Comment by Ashinch** [comment]
## Application information
- Package name: `com.oneplus.cloud`
- Version: 3.2.0 (400)
## Reason
- Path: `/storage/emulated/0/OSSLog/logs.csv`

**Comment by mwdotzom** [comment]
## Application information
- Package name: `com.oneplus.cloud`
- Version: 3.2.0 (400)
## Reason
- Path: `/storage/emulated/0/OSSLog/logs.csv`

**Comment by aliezoip** [comment]
## Application information - Package name: `com.oneplus.cloud` - Version: 3.2.0 (400) ## Reason - Path: `/storage/emulated/0/OSSLog`
