### ISSUE TITLE
[New rules request][AUTO] com.paprbit.dcoder

### ISSUE THREAD

**Issue by H-xiaoH** [RikkaApps/StorageRedirect-assets#3126]
## Application information
- Package name: `com.paprbit.dcoder`
- Display name: Dcoder
- Version: 1.8.7 (69)
## User rules
- `recommended`: {recommended}
- `verified`: yes
- Reason: 
### ObserverInfo
No observers.
## More information
- Android version: 10 (API 29)
- User language: zh_CN_#Hans
- Storage Redirect app version: 1.9.1.r1974.0521e9fe-arm64-v8a (19742)
## JSON Output
```
{
  "package": "com.paprbit.dcoder",
  "recommend": false,
  "verified": true,
  "authors": [
    "HxaioH"
  ]
}
```

**Comment by YandexStudio** [comment]
## Application information
- Package name: `com.paprbit.dcoder`
- Display name: Dcoder
- Version: 1.8.7 (69)
## User rules
- `recommended`: {recommended}
- `verified`: no
- Reason: 
### ObserverInfo
#### Directory: `Dcoder`
- `description`: `saved_files`
## More information
- Android version: 9 (API 28)
- User language: zh_CN
- Storage Redirect app version: 1.9.1.r1974.0521e9fe-arm64-v8a (19742)
## JSON Output
```
{
  "package": "com.paprbit.dcoder",
  "recommend": true,
  "verified": false,
  "authors": [
    "YandexStudio"
  ],
  "observers": [
    {
      "source": "Dcoder",
      "target": "Documents/Dcoder",
      "description": "saved_files",
      "call_media_scan": false,
      "add_to_downloads": true,
      "allow_child": true,
      "allow_temp": false
    }
  ]
}
```
