### ISSUE TITLE
[Invalid verified app][AUTO] com.android.settings

### ISSUE THREAD

**Issue by lengzhiyi** [RikkaApps/StorageRedirect-assets#3189]
## Application information
- Package name: `com.android.settings`
- Version: 7.2.90102 (7200031)
## Reason
- Path: `/storage/emulated/0/.uxip`

**Comment by cbr252522489** [comment]
## Application information
- Package name: `com.android.settings`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/Android/kwaiching.xml`
