### ISSUE TITLE
[Invalid verified app][AUTO] com.android.bluetooth

### ISSUE THREAD

**Issue by mwdotzom** [RikkaApps/StorageRedirect-assets#3190]
## Application information
- Package name: `com.android.bluetooth`
- Version: 10 (29)
## Reason
- Path: `/storage/emulated/0/bluetooth`

**Comment by jiz4oh** [comment]
## Application information
- Package name: `com.android.bluetooth`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/bluetooth`

**Comment by Cy324** [comment]
## Application information
- Package name: `com.android.bluetooth`
- Version: 9 (28)
## Reason
- Path: `/storage/emulated/0/bluetooth`
