### ISSUE TITLE
[Invalid verified app][AUTO] com.android.chrome

### ISSUE THREAD

**Issue by fairyex** [RikkaApps/StorageRedirect-assets#3194]
## Application information
- Package name: `com.android.chrome`
- Version: 78.0.3904.62 (390406237)
## Reason
- Path: `/storage/D430-B300/Android/data/com.android.chrome/files/Download`

**Comment by sdofuroe** [comment]
## Application information
- Package name: `com.android.chrome`
- Version: 78.0.3904.108 (390410837)
## Reason
- Path: `/storage/emulated/0/NAD/rule/com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity`
