### ISSUE TITLE
更新Magisk V20.2後StorageRedirect無法啟動伺服器...

### ISSUE THREAD

**Issue by Darkpurple** [RikkaApps/StorageRedirect-assets#3229]
更新Magisk V20.2後StorageRedirect無法啟動伺服器...

按了啟動..自動執行一堆指令後...顯示成功...
回到主頁卻又顯示無啟動狀態...
重新按啟動....自動執行一堆指令後...顯示成功......
然後一直不斷重覆....

手機是是Note 10+
Magisk v20.2 (有裝增強模式.)
環境是Android Q

**Comment by MasterCodeM** [comment]
试试安装ARM版本，不要安装ARM64版本。

**Comment by wqk317** [comment]
增强模块更新了，版本是22.1，专门修复这个问题的，可以试试 @Darkpurple
