### ISSUE TITLE
三星浏览器的不规范行为

### ISSUE THREAD

**Issue by timeawaying** [RikkaApps/StorageRedirect-assets#3237]
- 应用包名：com.sec.android.app.sbrowser
- 应用标题：三星浏览器
- 应用版本：11.0.00.89

- 规则问题描述：
![Screenshot_20200118-074057_Storage Redirect](https://user-images.githubusercontent.com/41231692/72653605-a99a7000-39c6-11ea-825b-ed0cf450b634.jpg)

- 规则修改建议：将其在根目录创建的文件重定向至Android/data/下应用的文件夹

- 规则代码修改建议：

**Comment by marcthas** [comment]
三星浏览器有两种的。
港版/国际版是纯净的。
但国行里面好像用了QQ浏览器的API，就是那个“关键词搜索-一搜即达”，所以会创建文件夹QQbrowser。
