### ISSUE TITLE
Currently Incorrect Rule: Pokemon Go (com.nianticlabs.pokemongo)

### ISSUE THREAD

**Issue by KieronQuinn** [RikkaApps/StorageRedirect-assets#3248]
## Basic information / 基本信息

> The following content is divided into required and optional. 
  Please delete content in parentheses after finishing the form. 
  If you know how to write rules in JSON format, recommended to submit 
  rules by pull request.
> 以下内容分为必填和选填，填写完毕好请记得删去括号内容，
  如了解如何使用 JSON 格式编写规则建议，建议使用 Pull Request 向我们提交规则。

- Application package name / 应用包名：com.nianticlabs.pokemongo
  
  
- Application title / 应用标题：Pokémon GO
  
  
- Application version / 应用版本：0.167.1

- If application exists non-standard file writing behavior / 应用是否存在不规范的文件写入情况：
  
Game checks for existence of:
/sdcard/MagiskManager (previous behaviour from before current version)
/sdcard/TWRP (TWRP recovery)
/sdcard/TitaniumBackup (TitaniumBackup app)
/sdcard/Fox (Red Fox recovery)
(and likely more)

As "evidence" for a rooted, and therefore cheating device.
  
- If application works normally when redirected / 重定向后应用能否继续正常工作：
  
Yes, though Snapshots require legitimate writing to the external storage to save for sharing.  
  
- What should be noticed when redirected / 重定向注意事项：
  
/sdcard/Pictures/PokemonGO is used to save snapshot photos so should be excluded.

**Comment by mbc07** [comment]
Worth mentioning that Pokémon Go leaves stuff on the internal storage once uninstalled, more specifically, `/sdcard/.backups/com.nianticlabs.pokemongo`
