### ISSUE TITLE
在miui中，对下载管理进行隔离出现的问题

### ISSUE THREAD

**Issue by Riddle233** [RikkaApps/StorageRedirect-assets#3256]
- 应用包名：com.android.providers.downloads.ui
- 应用标题：下载管理程序
- 应用版本：9.09.16.800003

- 规则问题描述：在miui里，对此应用开启隔离后，应用商店无法安装应用，主题管理无法安装主题
- 规则修改建议：应该只隔离下载管理创建的.DataStorge等文件夹

**Comment by RikkaW** [comment]
这个跟另外的人探索过了，暂时没有好的解决办法（
