### ISSUE TITLE
[提交新规则] Lucy

### ISSUE THREAD

**Issue by huanruomengyun** [RikkaApps/StorageRedirect-assets#3266]
- 应用 Id（package name）：

  com.mvizlab.lucy.android.en
  
- 应用显示名称：
  
  Lucy   (应用列表及存储空间隔离所显示名称为`Lucy`，全名`Lucy -The Eternity She Wished For-`)
 _(部分第三方汉化的汉化名称为Lucy和她所期望的永恒、Lucy和她期望的一切）_

- 应用版本：
  
  v2.3

- 是否滥用存储空间：
  
  仅官方版本（Google Play版本）不滥用存储空间。
 第三方版本（如第三方汉化版）并不遵循存储标准。

- 隔离后是否能正常工作/注意事项：
  
  能。

**Comment by RikkaW** [comment]
第三方版本就算了（
