### ISSUE TITLE
isolate swift backup will break it's feature of backing up ext data

### ISSUE THREAD

**Issue by QingKongBaiYu** [RikkaApps/StorageRedirect-assets#3283]
Configuration JSON:

> Tap in-app "upload icon" (added from v4.3.0), "Copy current settings to clipboard" and then paste to below.

```
{
  "label": "Swift Backup",
  "packageName": "org.swiftapps.swiftbackup",
  "authors": [
    "baiyu"
  ],
  "last_update": {
    "version_name": "3.1.3",
    "version_code": 387
  },
  "recommendation": "@unnecessary",
  "behaviors": "@standard"
}
```

Necessary information:

> 1. If there are errors in the existing rules, please indicate.
> 2. If there are some functions not work after isolation or there are special notes, please explain.
> 3. If possible, describe the behavior of using storage.
> 4. To "Accessible folders" rules and "Export isolated files" rules, please explain their role.

**Comment by RikkaW** [comment]
Does adding `Android/data` to accessible folders not work?

**Comment by QingKongBaiYu** [comment]
sorry, just find this opinion😅, I thought it was unselectable before.
