### ISSUE TITLE
qq8.3.3.4515所有在线隔离规则失效

### ISSUE THREAD

**Issue by mylovesaber** [RikkaApps/StorageRedirect-assets#3339]
设置 JSON：

> 轻触应用内的“上传图标”（于 v4.3.0 版本添加），轻触“复制当前设置到剪贴板”并粘贴到下面。

```
{
  "label": "QQ",
  "package": "com.tencent.mobileqq",
  "authors": [
    ""
  ],
  "last_update": {
    "timestamp": 1587090902,
    "version_name": "8.3.3",
    "version_code": 1376
  },
  "recommendation": "@recommended",
  "behaviors": [
    "@abuse"
  ]
}
```

补充必要的信息：

> 1. 如果现有的规则存在错误，请指出。

在线规则有错误，在管理器中q群文件下载的文件路径是:

/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/QQfile_recv/

该文件夹下的文件在文件管理器中可以看到，但在重定向软件中看到的是:

可访问的文件夹: 所有模板已经让qq可以使用

导出被隔离的文件: 在线规则中来源路径下看不到qq下载的文件，手动设置成文件所在的真实路径也看不见文件

结果就是重定向失败，Download下没有出现对应文件夹

**Comment by RikkaW** [comment]
https://sr.rikka.app/zh-hans/guide/tutorial.html#%E4%B8%8D%E8%A6%81%E6%BB%A5%E7%94%A8%EF%BC%81-2
