### ISSUE TITLE
希望补充 play版的网易云音乐 的 导出被隔离的音乐文件

### ISSUE THREAD

**Issue by listholy** [RikkaApps/StorageRedirect-assets#3346]
设置 JSON：

> 轻触应用内的“上传图标”（于 v4.3.0 版本添加），轻触“复制当前设置到剪贴板”并粘贴到下面。

```
{
  "label": "网易云音乐",
  "package": "com.netease.cloudmusic",
  "authors": [
    ""
  ],
  "last_update": {
    "timestamp": 1587296642,
    "version_name": "4.3.1",
    "version_code": 110
  },
  "recommendation": "@recommended",
  "behaviors": [
    "@abuse"
  ]
}
```

补充必要的信息：
play版的网易云音乐 没有导出文件位置，如图
![image](https://user-images.githubusercontent.com/50132662/79687293-ee110280-8278-11ea-9753-7fca7e774a1e.png)
MUSIC 文件 无
![image2](https://user-images.githubusercontent.com/50132662/79687331-27e20900-8279-11ea-93fa-facd7d5c7437.png)

> 1. 如果现有的规则存在错误，请指出。
> 2. 如果隔离后存在部分功能无法使用或有特别的注意事项，请说明。
> 3. 如果可以，介绍该应用使用存储空间的行为。
> 4. 对“可访问文件夹”规则和“导出被隔离的文件”规则，请说明它们的作用。

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/StorageRedirect-assets/blob/b33ca8455ad66af39453fa5a5060dfd51ac185b0/app_rule/apps/com.netease.cloudmusic.json#L27-L34

不是已经有了

**Comment by listholy** [comment]
不好意思，没有认真看说明，已找到设置😭
