### ISSUE TITLE
腾讯手机管家

### ISSUE THREAD

**Issue by ArthurCyy** [RikkaApps/StorageRedirect-assets#3426]
设置 JSON：

> 轻触应用内的“上传图标”（于 v4.3.0 版本添加），轻触“复制当前设置到剪贴板”并粘贴到下面。

```
{
  "label": "腾讯手机管家",
  "package": "com.tencent.qqpimsecure",
  "authors": [
    ""
  ],
  "last_update": {
    "timestamp": 1591008399,
    "version_name": "8.4.1",
    "version_code": 1402
  },
  "recommendation": "@recommended",
  "behaviors": [
    "@abuse"
  ]
}
```

补充必要的信息：隔离后会导致“清理加速”功能中部分垃圾文件无法扫描，如需使用该功能请谨慎开启

> 1. 如果现有的规则存在错误，请指出。
> 2. 如果隔离后存在部分功能无法使用或有特别的注意事项，请说明。
> 3. 如果可以，介绍该应用使用存储空间的行为。
> 4. 对“可访问文件夹”规则和“导出被隔离的文件”规则，请说明它们的作用。

**Comment by Henry-ZHR** [comment]
都会 root 了，还有人会用这种**软件？

**Comment by cyy0220** [comment]
> 都会 root 了，还有人会用这种**软件？

我用这个软件当QQ安全中心和领Q币用，它的**行为我用thanox等软件压制，每个软件的存在都有它的意义，请不要用自己的眼光随意做出过激的评判
