### ISSUE TITLE
[New rules request][AUTO] cn.ibuka.manga.ui

### ISSUE THREAD

**Issue by sjdhome** [RikkaApps/StorageRedirect-assets#36]
## Application information
 - Package name: `cn.ibuka.manga.ui`
 - Display name: 布卡漫画
 - Version: 2.3.0.26 (33751066)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.11.2-beta.r471.dcb7137 (471)
 ## JSON Output
 ```
 {
     "package": "cn.ibuka.manga.ui",
     "recommended": true,
     "verified": false,
     "authors": ["sjdhome"],
      "observers": [
 
     ]
 }
 ```

**Comment by coderfox** [comment]
## Application information
 - Package name: `cn.ibuka.manga.ui`
 - Display name: 布卡漫画
 - Version: 2.3.0.26 (33751066)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 #### Directory: `布卡保存图片`
 - `description`: `saved pictures`
#### Directory: `ibuka/down`
 - `description`: `downloaded manga`

 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: en_US
 - Storage Redirect app version: 0.12.0-beta.r478.f6e1d87 (478)
 ## JSON Output
 ```
 {
     "package": "cn.ibuka.manga.ui",
     "recommended": true,
     "verified": false,
     "authors": ["coderfox"],
      "observers": [
         {
             "description": "saved pictures",
             "source": "布卡保存图片"
         },
         {
             "description": "downloaded manga",
             "source": "ibuka/down"
         }
     ]
 }
 ```
