### ISSUE TITLE
企鹅电竞 启用存储空间隔离

### ISSUE THREAD

**Issue by Im-MyGO** [RikkaApps/StorageRedirect-assets#3623]
设置 JSON：

> 轻触应用内的“上传图标”（于 v4.3.0 版本添加），轻触“复制当前设置到剪贴板”并粘贴到下面。

```
{
  "label": "企鹅电竞",
  "package": "com.tencent.qgame",
  "authors": [
    ""
  ],
  "last_update": {
    "timestamp": 1604713495,
    "version_name": "6.4.0.526",
    "version_code": 526
  },
  "recommendation": "@recommended",
  "behaviors": [
    "@abuse"
  ]
}
```

补充必要的信息：

> 1. 如果现有的规则存在错误，请指出。
> 2. 如果隔离后存在部分功能无法使用或有特别的注意事项，请说明。
> 3. 如果可以，介绍该应用使用存储空间的行为。
> 4. 对“可访问文件夹”规则和“导出被隔离的文件”规则，请说明它们的作用。

**Comment by kisscent** [comment]
![Screenshot_20201107-130411538~2](https://user-images.githubusercontent.com/54803691/98432495-c5a80300-20f9-11eb-86da-feb69eb179f5.jpg)
