### ISSUE TITLE
Blank screen after updated latest version

### ISSUE THREAD

**Issue by lovitus** [RikkaApps/StorageRedirect-assets#3918]
在商店更新最新版本后，程序打不开，白屏，耗电很大。
重新安装应用，卸载模块。重新安装应用并清理数据 无效。
Only blank screen after updated latest version.
And can not be fixed after uninstalled magisk module,cleared data,or reinstalled the app.

Xiaomi mix2s , MIUI 11.0.3, android 10

**Comment by RikkaW** [comment]
If you are using Taichi (an Xposed framework), DO NOT add the Storage Isolation app to Taichi.
