### ISSUE TITLE
请问能不能制作一个基于Zygisk的模块？

### ISSUE THREAD

**Issue by ender-zhao** [RikkaApps/StorageRedirect-assets#3927]

**Comment by Gong-Mi** [comment]
> 

感觉不行
面具的zy有作用用功能。
不能全集用

**Comment by RikkaW** [comment]
1. Zygisk 缺少隐藏机制——内存中存在来自 `/data/adb` 的 so 是一个足够明显的自身遭到攻击的信号；对于存储空间隔离，这意味着在 zygisk 补上隐藏机制前，文件监视功能必须被放弃
2. Zygisk 还缺乏大范围为的测试以保证其稳定性——2021/11/16 才修好只要有多个 zygisk 模块就会坏掉问题
