### ISSUE TITLE
[问题]微信重定向后sdcard根目录位置，以及对Android文件夹的重定向

### ISSUE THREAD

**Issue by LinaChong** [RikkaApps/StorageRedirect-assets#3928]
根据文档，重定向后的储存空间为`/sdcard/Android/data/<package name>/sdcard/`
但是在开启重定向后，从微信内的“发送文件”看到出储存空间为`/sdcard/Android/data/com.tencent.mm/`
此时受`.nomedia`的影响，无法查看到该目录下的媒体文件。影响，微信自动创建的`tencent`文件夹也在`/sdcard/Android/data/com.tencent.mm/`下，与预期不符。

另外，在多个应用的`/sdcard/Android/data/<package name>/sdcard/`目录下，也存在
```
Android
├───data
├───media
└───obb
```
的目录结构，对/sdcard/Android/的访问不应该不受重定向影响吗

![问题一截图](https://i.ibb.co/HnzJ0cY/Screenshot-20211109-202512.png)
问题一截图  [截图1](https://i.ibb.co/HnzJ0cY/Screenshot-20211109-202512.png)
注：1111文件夹是我手动创建用于识别位置的。
![问题二截图](https://i.ibb.co/qJPWNNc/Screenshot-20211109-203535-1.png)
问题二截图 [截图2](https://i.ibb.co/qJPWNNc/Screenshot-20211109-203535-1.png)

**Comment by RikkaW** [comment]
问题一：无法复现。
问题二：它们是挂载点。
