### ISSUE TITLE
[问题]在应用管理中未能找到“隐藏应用列表“app

### ISSUE THREAD

**Issue by SaLTNEko** [RikkaApps/StorageRedirect-assets#3930]
## 基本信息

> 如了解如何使用 JSON 格式编写规则建议，建议使用 Pull Request 向我们提交规则。

- 应用 Id（package name）：

com.tsng.hidemyapplist
  
- 应用显示名称：
  隐藏应用列表

- 应用版本：
  
  可选。

- 是否滥用存储空间：
  
  否。

- 隔离后是否能正常工作/注意事项：
  
  并未找到对应app，无法隔离

**Comment by RikkaW** [comment]
一个应用程序使用存储空间需满足 请求了读或写存储权限 或 设备运行 Android 11 及以上。
如果你的设备运行更低版本的 Android 系统且应用没有请求存储权限，则它无法直接使用存储空间，也就没有隔离它的必要。
