### ISSUE TITLE
[New rules request][AUTO] com.google.android.apps.plus

### ISSUE THREAD

**Issue by HYHYatt** [RikkaApps/StorageRedirect-assets#4]
## Application information
 - Package name: `com.google.android.apps.plus`
 - Display name: Google+
 - Version: 10.0.0.186024514 (419576689)
 ## User rules
 - `recommended`: No
 - `verified`: Yes
 - Reason: 此为谷歌官方G+客户端，无非标准行为
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.1.1 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.11.1-beta.r463.95742ed (463)
 ## JSON Output
 ```
 {
     "package": "com.google.android.apps.plus",
     "recommended": false,
     "verified": true,
     "authors": ["HYHYatt"],
     "reason": {"zh_CN": "此为谷歌官方G+客户端，无非标准行为"},
     "observers": [
 
     ]
 }
 ```

**Comment by HYHYatt** [comment]
## Application information
 - Package name: `com.google.android.apps.plus`
 - Display name: Google+
 - Version: 10.0.0.186024514 (419576689)
 ## User rules
 - `recommended`: No
 - `verified`: Yes
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.1.1 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.11.1-beta.r463.95742ed (463)
 ## JSON Output
 ```
 {
     "package": "com.google.android.apps.plus",
     "recommended": false,
     "verified": true,
     "authors": ["HYHYatt"],
      "observers": [
 
     ]
 }
 ```

**Comment by sharp-tasting** [comment]
## Application information
 - Package name: `com.google.android.apps.plus`
 - Display name: Google+
 - Version: 10.1.0.187555767 (419623349)
 ## User rules
 - `recommended`: No
 - `verified`: Yes
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: en_US
 - Storage Redirect app version: 0.11.1-beta.r463.95742ed (463)
 ## JSON Output
 ```
 {
     "package": "com.google.android.apps.plus",
     "recommended": false,
     "verified": true,
     "authors": ["sharp-tasting"],
      "observers": [
 
     ]
 }
 ```
