### ISSUE TITLE
Not working with zygisk in magisk canary

### ISSUE THREAD

**Issue by Sygmstr** [RikkaApps/StorageRedirect-assets#4007]
Is there a version of this module that works with zygisk? If there isn't will it get support for it?

**Comment by dorawei** [comment]
same issue here, after upgrading to Android 12 and using zygisk Riru can't be loaded

**Comment by Sygmstr** [comment]
Hi,

Zygisk support for Storage Isolation is scheduled to launch this month. You
can use Magisk alpha (https://t.me/magiskalpha) which has old Magisk Hide
as as a temporary.

Thanks.

This is what i received when i messaged  the developer. Just go to their
telegram and install the alpha version

**Comment by liu269569205** [comment]
is supported ？this month will be over

**Comment by Sygmstr** [comment]
> is supported ？this month will be over

I don't think they haven't updated the module yet, so they probably haven't added support for it yet.
There's still a couple of days, so hope he keeps his promise

**Comment by RikkaW** [comment]
Zygisk support is almost finished, only some UI/UX content left.

**Comment by Sygmstr** [comment]
I want to know if you can give me contact information of the shamiko
developers since the newest update to my banking app made it stop working
