### ISSUE TITLE
小红书规则更新

### ISSUE THREAD

**Issue by xiangyu0** [RikkaApps/StorageRedirect-assets#4067]
设置 JSON：

> 轻触应用内的“上传图标”（于 v4.3.0 版本添加），轻触“复制当前设置到剪贴板”并粘贴到下面。

```
{
  "label": "小红书",
  "package": "com.xingin.xhs",
  "authors": [
    ""
  ],
  "last_update": {
    "timestamp": 1651036045,
    "version_name": "7.36.0.1",
    "version_code": 7360288
  },
  "recommendation": "@recommended",
  "behaviors": [
    "@abuse"
  ]
}
```

补充必要的信息：
隔离后提示已隔离0个文件夹，可能已经没有乱拉屎行为，应该没必要隔离了。
> 1. 如果现有的规则存在错误，请指出。
> 2. 如果隔离后存在部分功能无法使用或有特别的注意事项，请说明。
> 3. 如果可以，介绍该应用使用存储空间的行为。
> 4. 对“可访问文件夹”规则和“导出被隔离的文件”规则，请说明它们的作用。

**Comment by RikkaW** [comment]
<img width="329" alt="image" src="https://user-images.githubusercontent.com/12999176/166093895-c8077dfc-7e98-4ef5-8ff5-7ff9156a22ac.png">
亲自测试，你的信息有误。
