### ISSUE TITLE
大众点评目前暂时不会乱拉屎了，提示隔离0个文件夹

### ISSUE THREAD

**Issue by xiangyu0** [RikkaApps/StorageRedirect-assets#4070]
设置 JSON：

> 轻触应用内的“上传图标”（于 v4.3.0 版本添加），轻触“复制当前设置到剪贴板”并粘贴到下面。

```
{
  "label": "大众点评",
  "package": "com.dianping.v1",
  "authors": [
    ""
  ],
  "last_update": {
    "timestamp": 1651419612,
    "version_name": "10.60.3",
    "version_code": 106003
  },
  "recommendation": "@recommended",
  "behaviors": [
    "@abuse"
  ]
}
```

补充必要的信息：
目前该应用暂时不会乱拉屎
> 1. 如果现有的规则存在错误，请指出。
> 2. 如果隔离后存在部分功能无法使用或有特别的注意事项，请说明。
> 3. 如果可以，介绍该应用使用存储空间的行为。
> 4. 对“可访问文件夹”规则和“导出被隔离的文件”规则，请说明它们的作用。

**Comment by RikkaW** [comment]
<img width="330" alt="image" src="https://user-images.githubusercontent.com/12999176/166183907-53144cdb-144f-45fc-bcb1-7811559e0282.png">
