### ISSUE TITLE
ADM

### ISSUE THREAD

**Issue by WOLFRAZOR** [RikkaApps/StorageRedirect-assets#4081]
Configuration JSON:

> Tap in-app "upload icon" (added from v4.3.0), "Copy current settings to clipboard" and then paste to below.

```
{
  "label": "ADM",
  "package": "com.dv.adm",
  "last_update": {
    "timestamp": 1652010334,
    "version_name": "14.0.5",
    "version_code": 140005,
    "target_api": 31,
    "flags": 11
  },
  "recommendation": "@recommended",
  "behaviors": [
    "@abuse"
  ],
  "device_info": {
    "api": 29,
    "manufacturer": "Xiaomi",
    "brand": "Xiaomi",
    "model": "MI 6",
    "locale": "zh-Hans-CN"
  }
}
```

Necessary information:After isolation, any functions can use in normal.![Screenshot_20220508-194554.png](https://user-images.githubusercontent.com/93996192/167294775-14249eca-7d86-4f4f-b326-23b85f230fa1.png)![Screenshot_20220508-194732.png](https://user-images.githubusercontent.com/93996192/167294784-ede98c59-37fd-40a7-a512-98c0398b8f38.png)

> 1. If there are errors in the existing rules, please indicate.
> 2. If there are some functions not work after isolation or there are special notes, please explain.
> 3. If possible, describe the behavior of using storage.
> 4. To "Accessible folders" rules and "Export isolated files" rules, please explain their role.

**Comment by RikkaW** [comment]
#3511
