### ISSUE TITLE
轻启动

### ISSUE THREAD

**Issue by ArthurCyy** [RikkaApps/StorageRedirect-assets#4133]
设置 JSON：

> 轻触应用内的“上传图标”（于 v4.3.0 版本添加），轻触“复制当前设置到剪贴板”并粘贴到下面。

```
{
  "label": "轻启动",
  "package": "com.wpengapp.lightstart",
  "last_update": {
    "timestamp": 1652313197,
    "version_name": "2.23.3",
    "version_code": 22303,
    "target_api": 27,
    "flags": 3
  },
  "recommendation": "@unnecessary",
  "behaviors": [
    "@standard"
  ],
  "device_info": {
    "api": 31,
    "manufacturer": "Xiaomi",
    "brand": "Xiaomi",
    "model": "2106118C",
    "locale": "zh-CN"
  }
}
```

补充必要的信息：对于MIUI系统，建议关闭该应用中的“MIUI增强”功能，防止该应用在根目录创建miad文件。除此之外，该应用没有非标准的行为。

> 1. 如果现有的规则存在错误，请指出。
> 2. 如果隔离后存在部分功能无法使用或有特别的注意事项，请说明。
> 3. 如果可以，介绍该应用使用存储空间的行为。
> 4. 对“可访问文件夹”规则和“导出被隔离的文件”规则，请说明它们的作用。

**Comment by WOLFRAZOR** [comment]
我之前用这个的时候也是开隔离，但是系统是类原生。应该不会影响xposed组件（我用的时候是安装了xposed增强，但是并没有失效）（前提是先隔离再安装）
