### ISSUE TITLE
File Monitor 

### ISSUE THREAD

**Issue by TeaqariaWTF** [RikkaApps/StorageRedirect-assets#4173]
why is file monitor not working

![Screenshot_20220514-181123_Storage Isolation](https://user-images.githubusercontent.com/90970076/168434392-ca753226-13f7-46e5-814c-69338d42dfd5.png)
![Screenshot_20220514-181135_Storage Isolation](https://user-images.githubusercontent.com/90970076/168434430-6cfb9887-c869-4dff-99a7-741273ec8f5b.png)
![Screenshot_20220514-181155_Storage Isolation](https://user-images.githubusercontent.com/90970076/168434463-0b93719b-dca8-4f9f-8ee0-b7be1f553316.png)

**Comment by RikkaW** [comment]
RTFM
https://sr.rikka.app/guide/enhanced_mode/install/#zygisk

**Comment by TeaqariaWTF** [comment]
I'm already using this

![Uploading Screenshot_20220514-182433_Cygisk.png…]()

**Comment by TeaqariaWTF** [comment]
> RTFM https://sr.rikka.app/guide/enhanced_mode/install/#zygisk

I'm already using this

![Screenshot_20220514-182433_Cygisk](https://user-images.githubusercontent.com/90970076/168436411-6f322e29-726c-4e69-91e7-4c8df0857d42.png)

**Comment by RikkaW** [comment]
> In short, use the dedicated hiding module Shamiko to hide and never enable Enforce DenyList option.

Shamiko, not LSPosed :)

**Comment by TeaqariaWTF** [comment]
> > In short, use the dedicated hiding module Shamiko to hide and never enable Enforce DenyList option.
> 
> Shamiko, not LSPosed :)

yes i use it too


![Screenshot_20220514-183218_Cygisk](https://user-images.githubusercontent.com/90970076/168437616-fc98cd99-6313-4d25-9693-7050f8792457.png)

**Comment by RikkaW** [comment]
There is a file `/data/adb/shamiko/.tmp/status` that indicates if Shamiko is working. Please check if the content of the file is `1`. If it is not `1`, or there are other problem like the file does not exist, report the problem to LSPosed devs.

**Comment by TeaqariaWTF** [comment]
![Screenshot_20220514-184700_Materyal Dosyalar](https://user-images.githubusercontent.com/90970076/168439086-1e2555ff-b702-4c6c-8705-8e9d5553d01f.png)

**Comment by RikkaW** [comment]
Three dot menu - show hidden files
