### ISSUE TITLE
小精灵美化

### ISSUE THREAD

**Issue by SakuraKeke** [RikkaApps/StorageRedirect-assets#4216]
设置 JSON：

> 轻触应用内的“上传图标”（于 v4.3.0 版本添加），轻触“复制当前设置到剪贴板”并粘贴到下面。

```
{
  "verified": false,
  "device_info": {
    "locale": "zh-CN",
    "api": 31,
    "manufacturer": "Xiaomi"
  },
  "behaviors": [
    "@abuse"
  ],
  "recommendation": "@recommended",
  "package": "com.android.nineton.elfinapp",
  "non_standard_files": [
    ".DataStorage",
    ".UTSystemConfig",
    ".ntanalysis",
    ".oukdtft",
    "Android/data/com.snssdk.api.embed",
    "Android/data/com.tencent.ams",
    "ByteDownload",
    "Tencent",
    "backups"
  ],
  "last_update": {
    "target_api": 29,
    "flags": "read_storage, write_storage",
    "version_name": "6.3.3",
    "timestamp": 1655221711,
    "version_code": 63003
  }
}
```

补充必要的信息：

> 1. 如果现有的规则存在错误，请指出。
> 2. 如果隔离后存在部分功能无法使用或有特别的注意事项，请说明。
> 3. 如果可以，介绍该应用使用存储空间的行为。
> 4. 对“可访问文件夹”规则和“导出被隔离的文件”规则，请说明它们的作用。

**Comment by xiangyu0** [comment]
仓库没有更新吗，咋还是无此应用的规则

**Comment by RikkaW** [comment]
@xiangyu0 
![Screenshot_20220702-134414~2](https://user-images.githubusercontent.com/12999176/176988262-0f2936d6-3022-4422-842a-6d4311b04ed5.png)

**Comment by xiangyu0** [comment]
看错了😂，补充一个小妖精美化
{
  "device_info": {
    "api": 31,
    "manufacturer": "Xiaomi",
    "locale": "zh-CN"
  },
  "verified": false,
  "behaviors": [
    "@abuse"
  ],
  "recommendation": "@recommended",
  "non_standard_files": [
    ".DataStorage",
    ".UTSystemConfig",
    ".turing.dat",
    "Android/obj",
    "Download/com.xjlmh.classic",
    "Tencent",
    "maimob",
    "post",
    "tmp"
  ],
  "package": "com.xjlmh.classic",
  "last_update": {
    "target_api": 28,
    "flags": "read_storage, write_storage, android_writeable",
    "timestamp": 1656745803,
    "version_code": 545001,
    "version_name": "5.4.5.001"
  }
}
