### ISSUE TITLE
[New rules request][AUTO] com.bankcomm.Bankcomm

### ISSUE THREAD

**Issue by shanefengcn** [RikkaApps/StorageRedirect-assets#422]
## Application information
 - Package name: `com.bankcomm.Bankcomm`
 - Display name: 交通银行
 - Version: 3.2.5 (3205)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: zh_CN
 - Storage Redirect app version: 0.15.0-beta.r644.6ed158f (644)
 ## JSON Output
 ```
 {
  "package": "com.bankcomm.Bankcomm",
  "recommended": true,
  "verified": false,
  "authors": [
    "shanefengcn"
  ]
}
 ```

**Comment by sharp-tasting** [comment]
<img width="998" alt="2018-05-17 23 09 03" src="https://user-images.githubusercontent.com/13917842/40186360-74f0ddec-5a27-11e8-93f4-1fa32bd78bcb.png">
So what's the difference of these two?

**Comment by fython** [comment]
@sharp-tasting Only the first item's package name is correct. I didn't notice it since my OS is Windows 10 which is case-insensitive. I will delete the wrong one later.
