### ISSUE TITLE
USB Audio Player PRO

### ISSUE THREAD

**Issue by ArthurCyy** [RikkaApps/StorageRedirect-assets#4268]
设置 JSON：

> 轻触应用内的“上传图标”（于 v4.3.0 版本添加），轻触“复制当前设置到剪贴板”并粘贴到下面。

```
{
  "device_info": {
    "api": 32,
    "manufacturer": "Xiaomi",
    "locale": "zh-CN"
  },
  "verified": true,
  "behaviors": [
    "@standard"
  ],
  "recommendation": "@unnecessary",
  "non_standard_files": [],
  "package": "com.extreamsd.usbaudioplayerpro",
  "last_update": {
    "target_api": 30,
    "flags": "read_storage, write_storage",
    "timestamp": 1656911673,
    "version_code": 6077,
    "version_name": "6.0.7.7"
  }
}
```

补充必要的信息：在最新版本6.0.7.7上，应用已将UAPP文件夹的位置规范储存，无需开启隔离。
![Screenshot_20220704-131413_存储空间隔离](https://user-images.githubusercontent.com/37627147/177085828-282a3f63-e56d-4bf4-8bf8-0daf932ef50d.png)

> 1. 如果现有的规则存在错误，请指出。
> 2. 如果隔离后存在部分功能无法使用或有特别的注意事项，请说明。
> 3. 如果可以，介绍该应用使用存储空间的行为。
> 4. 对“可访问文件夹”规则和“导出被隔离的文件”规则，请说明它们的作用。

**Comment by lzqzzzz** [comment]
你好这个怎样使用？
