### ISSUE TITLE
[New rules request][AUTO] com.hxwj.wjjf

### ISSUE THREAD

**Issue by zhxhwyzh14** [RikkaApps/StorageRedirect-assets#455]
## Application information
 - Package name: `com.hxwj.wjjf`
 - Display name: 华夏万家金服
 - Version: 1.3.0 (30)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 求助，每个标准文件夹下面会创建一个
td-3的垃圾文件，求阻止
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: zh_CN
 - Storage Redirect app version: 0.15.4-beta.r667.ef83c85 (667)
 ## JSON Output
 ```
 {
  "package": "com.hxwj.wjjf",
  "recommended": true,
  "verified": false,
  "description": {
    "zh_CN": "求助，每个标准文件夹下面会创建一个\ntd-3的垃圾文件，求阻止"
  },
  "authors": [
    "zhxhwyzh14"
  ]
}
 ```

**Comment by fython** [comment]
@RikkaW

**Comment by zhxhwyzh14** [comment]
## Application information
 - Package name: `com.hxwj.wjjf`
 - Display name: 华夏万家金服
 - Version: 1.3.1 (31)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: zh_CN
 - Storage Redirect app version: 0.16.0-beta.r724.5ad0122 (724)
 ## JSON Output
 ```
 {
  "package": "com.hxwj.wjjf",
  "recommended": true,
  "verified": false,
  "authors": [
    "zhxhwyzh14"
  ]
}
 ```
