### ISSUE TITLE
[New rules request][AUTO] com.resilio.sync

### ISSUE THREAD

**Issue by ysc3839** [RikkaApps/StorageRedirect-assets#717]
## Application information
 - Package name: `com.resilio.sync`
 - Display name: Sync
 - Version: 2.5.9 (7471)
 ## User rules
 - `recommended`: No
 - `verified`: Yes
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: zh_CN
 - Storage Redirect app version: 0.16.5-beta.r758.8fce2c2-arm64-v8a (7582)
 ## JSON Output
 ```
 {
  "package": "com.resilio.sync",
  "recommended": false,
  "verified": true,
  "authors": [
    "ysc3839"
  ]
}
 ```

**Comment by Daohannce** [comment]
## Application information
 - Package name: `com.resilio.sync`
 - Display name: Sync
 - Version: 2.5.9 (7471)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: zh_CN
 - Storage Redirect app version: 0.16.5-beta.r758.8fce2c2-arm64-v8a (7582)
 ## JSON Output
 ```
 {
  "package": "com.resilio.sync",
  "recommended": true,
  "verified": false,
  "authors": [
    "Daohannce"
  ]
}
 ```
