### ISSUE TITLE
[New rules request][AUTO] com.jiongji.andriod.card

### ISSUE THREAD

**Issue by xhn16729** [RikkaApps/StorageRedirect-assets#879]
## Application information
 - Package name: `com.jiongji.andriod.card`
 - Display name: 百词斩
 - Version: 6.2.16 (6021600)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 #### Directory: `.DataStorage`
 - `description`: `saved_files`
#### Directory: `.UTSystemConfig`
 - `description`: `saved_files`
#### Directory: `baidu`
 - `description`: `saved_files`
#### Directory: `libs`
 - `description`: `saved_files`
#### Directory: `system`
 - `description`: `saved_files`

 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: en_US
 - Storage Redirect app version: 0.16.5-beta.r758.8fce2c2-arm64-v8a (7582)
 ## JSON Output
 ```
 {
  "package": "com.jiongji.andriod.card",
  "recommended": true,
  "verified": false,
  "authors": [
    "xhn16729"
  ],
  "observers": [
    {
      "source": ".DataStorage",
      "description": "saved_files"
    },
    {
      "source": ".UTSystemConfig",
      "description": "saved_files"
    },
    {
      "source": "baidu",
      "description": "saved_files"
    },
    {
      "source": "libs",
      "description": "saved_files"
    },
    {
      "source": "system",
      "description": "saved_files"
    }
  ]
}
 ```

**Comment by fython** [comment]
@xhn16729 请不要将应用产生的垃圾加入链接。
