### ISSUE TITLE
[New rules request][AUTO] fluddokt.opsu.android

### ISSUE THREAD

**Issue by FQrabbit** [RikkaApps/StorageRedirect-assets#970]
## Application information
 - Package name: `fluddokt.opsu.android`
 - Display name: opsu!
 - Version: 0.16.0b (36)
 ## User rules
 - `recommended`: No
 - `verified`: Yes
 - Reason: 这个游戏程序会按规范在根目录用应用名来存档歌曲和配置文件，不应该打开重定向.
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: zh_CN
 - Storage Redirect app version: 0.17.4-beta.r848.2384374d-arm64-v8a (8482)
 ## JSON Output
 ```
 {
  "package": "fluddokt.opsu.android",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN": "这个游戏程序会按规范在根目录用应用名来存档歌曲和配置文件，不应该打开重定向."
  },
  "authors": [
    "FQrabbit"
  ]
}
 ```

**Comment by fython** [comment]
@FQrabbit 能举一下它产生的目录例子吗？如果按照目前的说法 “在根目录用应用名来存档” 是不可以 verified 的。

**Comment by FQrabbit** [comment]
[![PBFR7F.md.png](https://s1.ax1x.com/2018/08/03/PBFR7F.md.png)](https://imgchr.com/i/PBFR7F)
我以为就像Telegram那样，在Sdcard根目录创建一个`Telegram`，只会在这个文件夹里面放文件都算规范🤔

**Comment by fython** [comment]
Telegram 那个也算不规范了。尽管 opsu 这么做可能使得放歌很麻烦，但还是要标记为不规范，保持不推荐重定向，让用户来决定吧。

**Comment by FQrabbit** [comment]
在根目录开文件夹只在里面一个放也算不规范啊原来，那你改一下吧，打扰了..

**Comment by fython** [comment]
@FQrabbit 好的，感谢提交规则和规则解释~
