### ISSUE TITLE
[New rules request][AUTO] com.android.updater

### ISSUE THREAD

**Issue by dzshzx** [RikkaApps/StorageRedirect-assets#985]
## Application information
 - Package name: `com.android.updater`
 - Display name: 系统更新
 - Version: 6.0.0 (60)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 #### Directory: `downloaded_rom`
 - `description`: `saved_files`

 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.17.4-beta.r848.2384374d-arm64-v8a (8482)
 ## JSON Output
 ```
 {
  "package": "com.android.updater",
  "recommended": true,
  "verified": false,
  "authors": [
    "dzshzx"
  ],
  "observers": [
    {
      "source": "downloaded_rom",
      "description": "saved_files"
    }
  ]
}
 ```

**Comment by dzshzx** [comment]
## Application information
 - Package name: `com.android.updater`
 - Display name: 系统更新
 - Version: 6.0.0 (60)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 #### Directory: `downloaded_rom`
 - `description`: `downloaded_files`

 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.17.4-beta.r848.2384374d-arm64-v8a (8482)
 ## JSON Output
 ```
 {
  "package": "com.android.updater",
  "recommended": true,
  "verified": false,
  "authors": [
    "dzshzx"
  ],
  "observers": [
    {
      "source": "downloaded_rom",
      "description": "downloaded_files"
    }
  ]
}
 ```

**Comment by dzshzx** [comment]
## Application information
 - Package name: `com.android.updater`
 - Display name: 系统更新
 - Version: 6.1.2 (61)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.18.2-beta.r945.67fb4022-arm64-v8a (9452)
 ## JSON Output
 ```
 {
  "package": "com.android.updater",
  "recommended": true,
  "verified": false,
  "authors": [
    "dzshzx"
  ]
}
 ```

**Comment by dzshzx** [comment]
## Application information
 - Package name: `com.android.updater`
 - Display name: 系统更新
 - Version: 6.1.2 (61)
 ## User rules
 - `recommended`: Yes
 - `verified`: No
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: zh_CN
 - Storage Redirect app version: 0.18.2-beta.r945.67fb4022-arm64-v8a (9452)
 ## JSON Output
 ```
 {
  "package": "com.android.updater",
  "recommended": true,
  "verified": false,
  "authors": [
    "dzshzx"
  ]
}
 ```

**Comment by fython** [comment]
不同系统上的 `com.android.updater` 表现会不同，暂不考虑添加。

**Comment by HuaJi2333DaDa** [comment]
## Application information
- Package name: `com.android.updater`
- Display name: 系统更新
- Version: 6.1.2 (61)
## User rules
- `recommended`: No
- `verified`: Yes
- Reason: 不建议重定向
### ObserverInfo
No observers.
## More information
- Android version: 7.0 (API 24)
- User language: zh_CN
- Storage Redirect app version: 1.0.2.r1204.f2752e1e-armeabi-v7a (12041)
## JSON Output
```
{
  "package": "com.android.updater",
  "recommended": false,
  "verified": true,
  "description": {
    "zh_CN": "不建议重定向"
  },
  "authors": [
    "HuaJi2333DaDa"
  ]
}
```

**Comment by Vstory** [comment]
## Application information - Package name: `com.android.updater` - Display name: 系统更新 - Version: 6.2.5 (64) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 8.1.0 (API 27) - User language: zh_CN - Storage Redirect app version: 1.2.2.r1370.6beebe9c-arm64-v8a (13702) ## JSON Output ``` {
  "package": "com.android.updater",
  "recommended": false,
  "verified": true,
  "authors": [
    "Vstory"
  ]
} ```

**Comment by Vstory** [comment]
## Application information - Package name: `com.android.updater` - Display name: 系统更新 - Version: 6.3.2 (67) ## User rules - `recommended`: No - `verified`: Yes - Reason:  ### ObserverInfo No observers. ## More information - Android version: 8.1.0 (API 27) - User language: zh_CN - Storage Redirect app version: 1.2.2.r1370.6beebe9c-arm64-v8a (13702) ## JSON Output ``` {
  "package": "com.android.updater",
  "recommended": false,
  "verified": true,
  "authors": [
    "Vstory"
  ]
} ```
