### ISSUE TITLE
[New rules request][AUTO] com.sukaiyi.bandwagonvps

### ISSUE THREAD

**Issue by cqhhy2001** [RikkaApps/StorageRedirect-assets#989]
## Application information
 - Package name: `com.sukaiyi.bandwagonvps`
 - Display name: Bandwagon VPS
 - Version: 2.4 (14)
 ## User rules
 - `recommended`: No
 - `verified`: Yes
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: en_GB
 - Storage Redirect app version: 0.17.4-beta.r848.2384374d-arm64-v8a (8482)
 ## JSON Output
 ```
 {
  "package": "com.sukaiyi.bandwagonvps",
  "recommended": false,
  "verified": true,
  "authors": [
    "cqhhy2001"
  ]
}
 ```

**Comment by XZ-Dev** [comment]
## Application information
 - Package name: `com.sukaiyi.bandwagonvps`
 - Display name: Bandwagon VPS
 - Version: 2.4 (14)
 ## User rules
 - `recommended`: No
 - `verified`: Yes
 - Reason: 
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: zh_CN
 - Storage Redirect app version: 0.17.4-beta.r848.2384374d-arm64-v8a (8482)
 ## JSON Output
 ```
 {
  "package": "com.sukaiyi.bandwagonvps",
  "recommended": false,
  "verified": true,
  "authors": [
    "XZ-Dev"
  ]
}
 ```
